### ISSUE TITLE
update to nativescript 5.2

### ISSUE THREAD

**Issue by iMarwan-k** [manijak/nativescript-carousel#100]
Hi @bradmartin,

Do you have a plan to update the tool to nativescript 5.

I'm facing an issue that since I updated to Angluar 7 and Nativescript 5.2, the presentation of each slides is messed up and I tried everything to fix it but no success. 

below is how the presentation looks like after the update

![issue](https://user-images.githubusercontent.com/19311396/52661499-cfbab480-2ec7-11e9-9dc9-aa6649551266.png)

Thanks

**Comment by bradmartin** [comment]
It's likely a layout issue opposed to the plugin itself. Care to share your UI markup?

**Comment by iMarwan-k** [comment]
sure
`
<GridLayout rows="*" *ngIf="deviceType === 'Phone'">
 <GridLayout row="0">
<CarouselItem *ngIf="assetList[1]" shadow="8" shadowColor="#000000" shadowOpacity="0.3" shadowOffset="-1">
                    <StackLayout id="eduCal">
                        <GridLayout rows="auto,auto,auto" class="contentBox" (tap)="onTap(assetList[1])">
                            <StackLayout row="0" class="imgBox" horizontalAlignment="center" verticalAlignment="center">
                                <Image src="{{constants.devRootUrlHead}}/Web/content/images/homeFeaturedAssets/{{assetList[1].imagePath}}"></Image>
                            </StackLayout>

                            <Label row="1" text="{{assetList[1].resourceHeader}}" textWrap="true" class="boxTitle" horizontalAlignment="center" verticalAlignment="center"></Label>
                        
                            <StackLayout row="2" class="titleAbstractSiloBox">
                                <StackLayout class="textBox">
                                    <Label text="{{assetList[1].displayName}}" textWrap="true" class="textTitle"></Label>
                                    <Label text="{{assetList[1].abstractText}}" textWrap="true" class="textAbstract"></Label>
                                </StackLayout>

                                <StackLayout orientation="horizontal" class="siloBox" horizontalAlignment="right" *ngIf="getDisplayValue(assetList[1])">
                                    <Label top="10" left="290" [text]="getDisplayValue(assetList[1])" textWrap="true" class="siloWord"></Label>
                                    <Label top="10" left="300" text="&#xf101;" textWrap="true" class="fa rightArrow" verticalalignment="center"></Label>
                                </StackLayout>                    
                            </StackLayout>
                        </GridLayout>
                    </StackLayout>
                </CarouselItem>
</GridLayout>
</GridLayout>
`

The code above is inside a tabview

**Comment by manijak** [comment]
You do have a `<Carousel>` wrapper around your `<CarouselItem>` component right?

**Comment by bradmartin** [comment]
I've updated an app to 5.2 from 5.1 and it works fine. So I'm guessing the implementation is a little off here.

**Comment by iMarwan-k** [comment]
> You do have a `<Carousel>` wrapper around your `<CarouselItem>` component right?

Yes

**Comment by iMarwan-k** [comment]
> I've updated an app to 5.2 from 5.1 and it works fine. So I'm guessing the implementation is a little off here.

But it works fine with 4.2, so I was wondering why it gets off when I use an image that source from internet. However, when I use image that source from local everything is working fine.

**Comment by manijak** [comment]
I have a feeling that your problem lies elsewhere. Your question is directed towards why the image component only works with local images and not with remote ones, nothing to do with the carousel itself... 

Make sure first that the image component can load the remote images with the propperly formatted source parh and not hardcoded. 

From the example above the image source value looks a bit off. Not 100% sure you can combine string and property values like that...

**Comment by iMarwan-k** [comment]
> I have a feeling that your problem lies elsewhere. Your question is directed towards why the image component only works with local images and not with remote ones, nothing to do with the carousel itself...
> 
> Make sure first that the image component can load the remote images with the propperly formatted source path and not hardcoded.
> 
> From the example above the image source value looks a bit off. Not 100% sure you can combine string and property values like that...

I understand your point, but my problem doesn't exist with 4.2, only when I upgraded to 5.2 the layout gets off. so if the image was wrong, it should not work with either of them.

You mentioned that there is something wrong with my image, can you tell me what is it?

**Comment by bradmartin** [comment]
4.2 to 5.2 is a major bump which introduces breaking changes typically following semver. So it's possible something in NS changed itself. Hope that helps understanding some 😄

**Comment by iMarwan-k** [comment]
> 4.2 to 5.2 is a major bump which introduces breaking changes typically following semver. So it's possible something in NS changed itself. Hope that helps understanding some 😄

You are indeed correct, Nativescript changes how GridLayout, StackLayout, and Image work
