### ISSUE TITLE
iosOverflowSafeArea works incorrectly

### ISSUE THREAD

**Issue by 3DtuningProduction** [manijak/nativescript-carousel#102]
Hi 
Trying to make a full-screen carousel
Very strange error is obtained
1 screen
http://prntscr.com/mwfq5z
2 screen
http://prntscr.com/mwfqze
How do you think this problem can be solved?
Thank you in advance

**Comment by manijak** [comment]
Hmmm. I've recently had some issues similar to this. Have no idea what is causing it. Could be the iphone x safe-area calculation.

**Comment by manijak** [comment]
Duplicate of https://github.com/manijak/nativescript-carousel/issues/114
Closing
