### ISSUE TITLE
preselect Item different from first

### ISSUE THREAD

**Issue by aalonzi** [manijak/nativescript-carousel#104]
I see "selectedPage" Attribute and I try to use It in Manual CarouselItem, like:
`<ns:Carousel height="100%" width="100%" selectedPage="2" indicatorColor="#fff000" finite="true" bounce="false" showIndicator="true" verticalAlignment="top" android:indicatorAnimation="swap" color="white">`

The indicator is correctly selected, but the displayed item is always the first one.  Why?

Thank you

**Comment by prinzt** [comment]
I have the same problem (iOS, not tested on Android).
If you set finite to false it works. So finite: true seems to break selectedPage

**Comment by manijak** [comment]
Duplicate, same as: https://github.com/manijak/nativescript-carousel/issues/106

Closing
