### ISSUE TITLE
Android indicator not centered.

### ISSUE THREAD

**Issue by ronheiney** [manijak/nativescript-carousel#105]
Using latest plugin and Vue the indicator is not centered, if I wrap with grid it is centered at the top.

`              <Carousel #carousel ios:finite="true" ios:bounce="false" showIndicator="true" height="240" 
                indicatorColor="#66ccff" indicatorColorUnselected="#cceeff" width="80%">
                <CarouselItem backgroundColor="red" height="100%">
                    <Label class="h2 text-center" color="white" textWrap="true" text="1"></Label>
                </CarouselItem>
                <CarouselItem backgroundColor="purple">
                    <Label class="h2 text-center" color="white" textWrap="true" text="2"></Label>
                </CarouselItem>
              </Carousel>`

<img width="360" alt="Screen Shot 2019-04-13 at 12 26 31 PM" src="https://user-images.githubusercontent.com/1004139/56083883-10f81380-5de8-11e9-8ac3-e4f6696fba67.png">

**Comment by comporell** [comment]
Try warpping the carousel with a <Gridlayout rows="auto">..</Gridlayout > and see if it works for you.

**Comment by manijak** [comment]
Yes the Carousel on android still needs to be wrapped in a GridLayout for the indicator to overlap.
