### ISSUE TITLE
"finite = true" breaks "selectedPage" (Vue)

### ISSUE THREAD

**Issue by prinzt** [manijak/nativescript-carousel#106]
When setting finite to true it is not possible to preselect a carousel page with selectedPage. 
selectedPage gets ignored. Setting finite to false (or not setting it at all) makes selectedPage to work again.
Tested on an iPhone SE with nativescript-vue

**Comment by gle6as** [comment]
I found workaround for this:

```vue
<template>
  <Page @loaded="onPageLoaded">
    <Carousel :finite="loaded" ref="carousel">...</Carousel>
  </Page>
</template>

<script>
...
onPageLoaded() {
  this.$refs.carousel.nativeView.selectedPage = 1
  this.loaded = true
  this.$nextTick(() => {
    this.$refs.carousel.nativeView.refresh()
  })
}
...
</script>
```

**Comment by romandragan** [comment]
@manijak,

@gle6as's workaround is not working anymore with the latest plugin version.

**Comment by bunower** [comment]
When does it solved?
It doesnt work for me either.
