### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by shiv19** [manijak/nativescript-carousel#111]
```js
exports.selectedPageProperty = new view_1.Property({
    name: 'selectedPage',
    defaultValue: 0,
    valueConverter: function (value) {
        return +value;
    },
    valueChanged: function (view, oldValue, newValue) {
        view.selectedPage = newValue;
    }
});
```

this part of the plugin is somehow triggering a value change event recursively and causing max call stack size exceeded error.

[log.txt](https://github.com/manijak/nativescript-carousel/files/3209994/log.txt)

**Comment by manijak** [comment]
Sorry for the late reply. But where did this error occur? Did it happen in the included demo apps? Just trying to figure out if it is app or plugin related issue. 

Our demo apps have examples where a user can select a specific page while we listen to the events. I could not see issues like this while testing...
