### ISSUE TITLE
iOS SafeArea not works

### ISSUE THREAD

**Issue by pboulch** [manijak/nativescript-carousel#114]
Hi, 

I tried to use this plugin on iPhone X. Each item of my carousel must take the full size of the screen (and therefore cover the SafeArea). The `Carousel` covers the two SafeArea well but the `CarouselItem` only covers the bottom SafeArea. 

```
<ns:Carousel id="myCarousel" height="100%" width="100%" color="white" pageChanged="myChangeEvent"
    pageTapped="mySelectedEvent" android:indicatorAnimation="slide" indicatorColor="#fff" background="yellow"
    showIndicator="true">
        <ns:CarouselItem *ngFor="let item of myDataArray" background="blue">
        <GridLayout background="red">
            <Label [text]="item"></Label>
        </GridLayout>
    </ns:CarouselItem>
    
</ns:Carousel>
```

![image](https://user-images.githubusercontent.com/40267808/59365851-912fec00-8d39-11e9-8e6d-24e8a6d35c22.png)

**Comment by darkmantle** [comment]
Any more information / updated regarding this?

**Comment by manijak** [comment]
Version 6.1.0 published that should fix safe-area issue.

**Comment by MateusSpadari** [comment]
Hello guys, sorry for reopening this. But im having the same issue here, but in my case all the screens of the carousel works fine, except one (the right picture below). Its seems that in this specific screen the IOS safe area does not apply and i don't know why ! the text and images are just an angular *ngFor.

<img width="200" alt="Captura de Tela 2020-02-10 às 10 55 02" src="https://user-images.githubusercontent.com/38570811/74155749-db80aa00-4bf3-11ea-8e4e-818892b07bc2.png"><img width="200" alt="Captura de Tela 2020-02-10 às 10 55 10" src="https://user-images.githubusercontent.com/38570811/74155760-de7b9a80-4bf3-11ea-97cc-9bb74675e08c.png">

**Comment by manijak** [comment]
Hmmm, that is strange. Only the third slide is like that, the 4th is okay? I am thinking it might have something to do with the pre-rendering of the views. In your case the third slide is the one that gets rendered when reaching slide nr 2. So my idea is that slides that get rendered in runtime, fail to apply the overflow...

Just for testing purposes, if you only have 3 slides, are all of them rendered correctly? Also, if you have say 5, are slides 3 & 4 rendered incorrectly?
