### ISSUE TITLE
UI issue on iOS: UIScrollView component bounces vertically 

### ISSUE THREAD

**Issue by andrewbeng89** [manijak/nativescript-carousel#115]
Hi @manijak thanks so much for looking this issue! 😄 For easy reference and context, here’s a screen recording of the issue: https://drive.google.com/open?id=1Ank3zti3VIWv8SCge6bdvRJ2F0PITlNR

The app is implemented with nativescript-vue and the issue my team is trying to fix is in removing the bounce effect when swiping between `CarouselItem`s. This becomes apparent when horizontal scrolling/swiping is not exactly along the x-axis. My suspicion is that this is caused by the ios `UIScrollView` (the `bounces` property) in `DKCarouselView`, or the `CarouselItem` container - `DKClickableImageView` (I believe this is a `StackLayout` component) having a height larger than the `UIScrollView` container. In either case, I am wondering if the native ios properties can be accessed or set via the NS `Carousel` or `CarouselItem` components.

This is the tree structure of iOS UI components: the `UIView` child of `DKClikcableImageView` has a height of 1270 DIP, which might be causing the `UIScrollView` to bounce vertically (unintended behaviour):

![image](https://user-images.githubusercontent.com/2418932/60432798-77304d80-9c03-11e9-9a35-c50ecb4ab852.png)
![image](https://user-images.githubusercontent.com/2418932/60432826-8ca57780-9c03-11e9-94e4-37586b466588.png)

**Comment by andrewbeng89** [comment]
Hi @manijak I've invited you to view the debug repo: https://github.com/andrewbeng89/nativescript-carousel-bounce-debug/invitations

I'm using a `GridLayout` (with different bgColors) containing an `ActivityIndicator`, still with the same behaviour:

![image](https://user-images.githubusercontent.com/2418932/60442726-f3359000-9c19-11e9-8da6-ed21f48fd40f.png)

**Comment by manijak** [comment]
Thanks for the demo app. There is a similar issue on other tns variants, so its not just Vue related. The behavior can be different tho. On Vue, like in your case, you can scroll up/down while changing slides. That gives the "bounce effect". 

On vanilla tns using typescript, same example, here it doesn't allow you to scroll up/down, but the carousel-items get random margin/padding on the top while changing pages. 

I have not found the cause, but do have a solution. It's an odd one, but it works. You need to add a slight padding to the wrapper element for the child elements to properly render. 
Will have to seek help from someone at nativescript to figure what is going on here. 

**Solution/Hack:**

- The `Carousel` needs a wrapper element, in your case the `GridLayout`. 
- Add a css-class to the GridLayout e.g. `class="grid-carousel-padding"`. 
- Create the css-class: 
```
.grid-carousel-padding {
  padding: 0.1;
}
```

**Comment by andrewbeng89** [comment]
Thanks for the quick feedback for the fix, it works like a charm!

The following css props adjusts for the layout on the `top` and `bottom` of the wrapper, without affecting `left` and `right`:

```css
  padding: 0.1 0;
  margin: -0.1 0;
```

**Comment by manijak** [comment]
Version 6.1.0 published that should fix safe-area issue. No need to use the css-hack any more.
