### ISSUE TITLE
 space between carousel items

### ISSUE THREAD

**Issue by Vinaykummar** [manijak/nativescript-carousel#117]
hi, can you please add a property for spacing between the item. 
Reference example in link below

https://camo.githubusercontent.com/7590ec7e6b705a6e8e381397247d576c6db72147/68747470733a2f2f692e696d6775722e636f6d2f653157625a63752e676966

**Comment by manijak** [comment]
You have already requested this feature: https://github.com/manijak/nativescript-carousel/issues/42
If there is time, I will do it. Otherwise PRs are welcome.

Closing this...
