### ISSUE TITLE
Getting Android-namespace error in d.ts

### ISSUE THREAD

**Issue by adilsaeed31** [manijak/nativescript-carousel#118]
Hi,
I am using your plugin but it's working fine for me, but it was giving me error due to this I am unable to generate the production build. 

```
ERROR in node_modules/nativescript-carousel/carousel.d.ts(42,54): error TS2304: Cannot find name 'androidx'.
node_modules/nativescript-carousel/carousel.d.ts(51,18): error TS2503: Cannot find namespace 'android'.
node_modules/nativescript-carousel/carousel.d.ts(54,51): error TS2304: Cannot find name 'androidx'.
```

Can you tell me how to resolve this I am unable to generate apk and ipa file due to this issue. 

Thank you.

plugin version : 4.2.6
tns-core-module: 6.0.1
nativescript 6 

Using this plugin for nativescript angular

**Comment by manijak** [comment]
Do you perhaps have a `"skipLibCheck": true` in your tsconfig.json? If not add it, and try again.

**Comment by adilsaeed31** [comment]
Hi

Yes it's Working now, but any other solution except this.

Thanks
Adil

**Comment by manijak** [comment]
The only other solution I know of is to install `tns-platform-declarations` package and add android references to a `references.d.ts` file in the root of your project:
```
/// <reference path="./node_modules/tns-platform-declarations/android.d.ts" />
```
But the docs state the following:

> d.ts files require a lot of memory and CPU. Consider adding skipLibCheck option to tsconfig file.
