### ISSUE TITLE
Image iOS Safe Area

### ISSUE THREAD

**Issue by darkmantle** [manijak/nativescript-carousel#119]
I know there is an open issue, but this is a bit more of a specific issue.

So I have the following code. When I inspect the elements, the iosOverflowSafeArea property doesn't seem to be passed into the <image> tag, although the property on the Carousel/CarouselItem shows up within elements.

Is this to do with this library or another problem? THis is the best carousel/spinner there is, except the safe area issue.

**Comment by darkmantle** [comment]
Update. It works now, but some images don't stretch properly, so part of the previous image is visible behind the statusbar after the first few images.

**Comment by manijak** [comment]
You didn't provide any code... so I don't know what you did for it to work. 

You can try and set the following property on the Image `iosOverflowSafeArea="true"`

**Comment by darkmantle** [comment]
Sorry. I set that property on both the image and the CarouselItem, yet the bug above (part of the previous image is visible) still happens. It's hard to explain really, but the first few images are fine, and then either the previous image seems to stay behind the StatusBar, or it goes back to the default gradient that is there when you don't have the safeArea property.

**Comment by manijak** [comment]
Version 6.1.0 published that should fix safe-area issue.

**Comment by darkmantle** [comment]
Still have the same problem, plus now images no longer stretch to fit.
