### ISSUE TITLE
PagerAdapter#notifyDataSetChanged Error

### ISSUE THREAD

**Issue by kentplaza** [manijak/nativescript-carousel#12]
Everytime my page topmost().goback() will hit error PagerAdapter#notifyDataSetChanged! Expected adapter item count:5, found 10 Pager id:2....

I found when the page loaded from cache/history will hit it. like press in back button or app awake from backgound.

**Comment by manijak** [comment]
Hmmm. Strange, I just published an app for both iOS and Android with this plugin. Works fine. We had a similar issue before, but we patched it.

Could you please give me some more information on how I can reproduce this?
- Plugin version you are using
- Android version you are testing on
- Is this vanilla NativeScript or NativeScript Angular?

**Comment by kentplaza** [comment]
Tns version: 2.5
My android Version 6.0.1
Vanila Nativescript

![screenshot](https://cloud.githubusercontent.com/assets/9535716/23399490/5fb892e8-fddb-11e6-9f66-b4f57d53ee25.png)

**Comment by manijak** [comment]
Thanks. Can you please check the version of the plugin you are using?
Make sure it is the latest one https://www.npmjs.com/package/nativescript-carousel

**Comment by kentplaza** [comment]
"nativescript-carousel": "^2.3.1",

**Comment by manijak** [comment]
Thanks. I presume you are using the Carousel with binding and template? 
How and where do you set the binding to the carousel items? Is it in the `loaded` event of the view or somewhere else?

**Comment by kentplaza** [comment]
Yes. In the page Loaded event.

**Comment by manijak** [comment]
I've tried to reproduce this error on two apps, but no luck. Did you try running the demo app included in the plugin here on git?

Or if your could create a sample app that reproduces the issue so I can take a look?

**Comment by kentplaza** [comment]
The problem solved by remove the item when page load.

**Comment by manijak** [comment]
Hmmm. so you populated the Carousel items, every time the page loaded? 
I will try and reproduce this. I usually have caching so data is only populated only once, not on every load.

**Comment by kentplaza** [comment]
Yupe.. now it load every time.

It fine in my case, cause i need the data to be latest so that have to reload everytime.
