### ISSUE TITLE
Padding between ActionBar and Carousel content

### ISSUE THREAD

**Issue by GMatshwane** [manijak/nativescript-carousel#121]
There seems to be padding between the ActionBar and the Carousel content. This is only visible on iOS. Any ideas why this could be happening?

**Comment by manijak** [comment]
Could you provide an example?

**Comment by GMatshwane** [comment]
Please see code 

<ActionBar class="action-bar" [flat]='platform'>
    <label *ngIf="isTablet" text="Work Execution Platform" class="action-bar-title"></label>
    <label *ngIf="!isTablet" text="WEP" class="action-bar-title"></label>
    <NavigationButton *ngIf="platform" icon="res://online"></NavigationButton>
    <ActionItem ios.position="left" icon="res://online" *ngIf="!platform"></ActionItem>
    <ActionItem ios.position="right" icon="res://updated" (tap)="onSyncTap()"></ActionItem>
    <ActionItem ios.position="right" (tap)="openDrawer()" icon="res://menu"></ActionItem>
</ActionBar>
<RadSideDrawer [drawerLocation]="currentLocation" [showOverNavigation]="true"
    [drawerContentSize]='isTablet ? "500" : "330"'>

    <StackLayout tkDrawerContent class="sideStackLayout">
        <StackLayout>
            <StackLayout class="bottom-separator" *ngFor="let item of drawerContent, let i = index">
                <GridLayout class="p-10" columns="auto * auto" height="50" (tap)="onItemSelect( i )">
                    <StackLayout col="0" class="m-r-10">
                        <label [text]="item.icon | fonticon" class="fa sub-image"></label>
                    </StackLayout>
                    <StackLayout col="1">
                        <Label [text]="item.title" class="user-name"></Label>
                    </StackLayout>
                    <StackLayout col="2" class="m-r-10" horizontalAlignment="right" (tap)="openDrawer()"
                        *ngIf='i === 0'>
                        <label [text]="'fa-times' | fonticon" class="fa sub-image" color="#8497b0"></label>
                    </StackLayout>
                </GridLayout>
            </StackLayout>
        </StackLayout>
    </StackLayout>

    

    <GridLayout class="top-separator" tkMainContent rows="* 3* auto" [backgroundColor]='isTablet ? "#fff" : "#f2f2f2"'>
        <GridLayout *ngIf='!isCoal' row="0" class="bottom-separator" verticalAlignment="top" >
            <Carousel debug="true" height="100%" width="100%" color="white" pageChanged="myChangeEvent"
                backgroundColor="yellow" pageTapped="mySelectedEvent" indicatorColor="#c5b25f"
                [indicatorOffset]=' isTablet ? "0,10" : "0,10"' indicatorRadius="3" indicatorColorUnselected="white"
                finite="true" bounce="false" showIndicator="true" android:indicatorAnimation="WORM">

                <CarouselItem>
                    <GridLayout columns="* 3*" rows="*" class="app-name-stack-back m-t-0" verticalAlignment="middle">
                        <GridLayout row="0" col="0" horizontalAlignment="center">
                            <Image src="res://weplogo" style="opacity: 0.1"></Image>
                        </GridLayout>
                        <GridLayout rows="auto auto" col="1" row="0" class=" p-l-10" verticalAlignment="middle">
                            <label row="0" [text]='"Welcome " + claims.name' color="white"
                                [class.tablet-carousel-text]="isTablet" [class.phone-carousel-text]="!isTablet"></label>
                            <label row="1" textWrap="true"
                                [text]='claims.JobTitle + ", " + claims.Department + " Good"' color="#bfbfbd"
                                [class.tablet-carousel-text]="isTablet" [class.phone-carousel-text]="!isTablet"></label>
                        </GridLayout>
                    </GridLayout>
                </CarouselItem>
                <CarouselItem>
                    <GridLayout rows="*">
                        <Image src="res://landing" row="0" stretch="aspectFill">
                        </Image>
                        <StackLayout class="image-bright" row="0"></StackLayout>
                        <GridLayout rows="auto auto" row="0" class="m-b-10 p-l-10" verticalAlignment="bottom">
                            <label [class.tablet-carousel-text]="isTablet" [class.phone-carousel-text]="!isTablet"
                                row="0" textWrap="true"
                                text="Find out more about the Platform and features currently available"
                                color="white"></label>
                            <label [class.tablet-carousel-text]="isTablet" [class.phone-carousel-text]="!isTablet"
                                row="1" textWrap="true" text="" color="white"></label>
                        </GridLayout>
                    </GridLayout>
                </CarouselItem>
            </Carousel>

        </GridLayout>
        <GridLayout *ngIf='isCoal' row="0" rows="*">
            <Carousel row="0" debug="true" height="100%" width="100%" color="white" pageChanged="myChangeEvent"
                pageTapped="mySelectedEvent" indicatorColor="#c5b25f" [indicatorOffset]=' isTablet ? "0,10" : "0,10"'
                indicatorRadius="3" indicatorColorUnselected="white" finite="true" bounce="false" showIndicator="true"
                android:indicatorAnimation="WORM">

                <CarouselItem>
                    <GridLayout columns="* 3*" rows="*" class="app-name-stack-back">
                        <GridLayout row="0" col="0" horizontalAlignment="center">
                            <Image src="res://weplogo" style="opacity: 0.1"></Image>
                        </GridLayout>
                        <GridLayout rows="auto auto" col="1" row="0" class="p-t-5 p-l-10" verticalAlignment="middle">
                            <label row="0" [text]='"Welcome " + claims.name' color="white"
                                [class.tablet-carousel-text]="isTablet" [class.phone-carousel-text]="!isTablet"></label>
                            <label row="1" textWrap="true"
                                [text]='claims.JobTitle + ", " + claims.Department + " - Good"' color="#bfbfbd"
                                [class.tablet-carousel-text]="isTablet" [class.phone-carousel-text]="!isTablet"></label>
                        </GridLayout>
                    </GridLayout>
                </CarouselItem>
                <CarouselItem>
                    <GridLayout rows="*">
                        <Image src="res://landing" row="0" stretch="aspectFill">
                        </Image>
                        <StackLayout class="image-bright" row="0"></StackLayout>
                        <GridLayout rows="auto auto" row="0" class="m-b-10 p-l-10" verticalAlignment="bottom">
                            <label [class.tablet-carousel-text]="isTablet" [class.phone-carousel-text]="!isTablet"
                                row="0" textWrap="true"
                                text="Find out more about the Platform and features currently available"
                                color="white"></label>
                            <label [class.tablet-carousel-text]="isTablet" [class.phone-carousel-text]="!isTablet"
                                row="1" textWrap="true" text="" color="white"></label>
                        </GridLayout>
                    </GridLayout>
                </CarouselItem>
            </Carousel>
        </GridLayout>
        <StackLayout row="1" class="container">
            <ScrollView>
                <StackLayout *ngIf="isCoal">
                    <StackLayout class="content top-separator">
                        <GridLayout rows="* auto" columns="auto 4* *" class="m-5" [class.tablet-content-grid]="isTablet"
                            [class.phone-content-grid]="!isTablet">
                            <StackLayout row="0" rowSpan="2" col="0" class="icon-stack"
                                [class.tablet-icon-stack]="isTablet" [class.phone-icon-stack]="!isTablet">
                                <label color="white" [text]="'ion-wrench' | fonticon" class="ion"
                                    [class.phone-icon]="!isTablet" [class.tablet-icon]="isTablet"
                                    horizontalAlignment="center"></label>
                            </StackLayout>
                            <label [class.phone-header-text]="!isTablet" [class.tablet-header-text]="isTablet"
                                verticalAlignment="top" class="m-l-5 header" text=" Requests" row="0" col="1"
                                (tap)="onItemTap( 0 )"></label>
                            <label [class.phone-description-text]="!isTablet" [class.tablet-description-text]="isTablet"
                                class="description-text m-l-5" text="Create or View Requests" row="1"
                                col="1"></label>
                            <GridLayout row="0" rowSpan="2" col="2" columns="* *">
                                <StackLayout col="0" *ngIf="isTablet" (tap)="onItemTap( 0 )">
                                    <label [class.phone-icon]="!isTablet" [class.tablet-icon]="isTablet"
                                        horizontalAlignment="center" class="ion header"
                                        [text]="'ion-android-search' | fonticon"></label>
                                </StackLayout>
                                <StackLayout col="1" (tap)="onAddTap( 0 )">
                                    <label [class.phone-icon]="!isTablet" [class.tablet-icon]="isTablet"
                                        horizontalAlignment="center" class="ion header"
                                        [text]="'ion-android-add' | fonticon"></label>
                                </StackLayout>
                            </GridLayout>
                        </GridLayout>
                        <StackLayout>
                            <StackLayout class="m-x-5 m-t-10">
                                <GridLayout columns="* *" width="50%" horizontalAlignment="left">
                                    <StackLayout col="0">
                                        <label text="Most recent" horizontalAlignment="left" (tap)="onRecentTap()"
                                            [class.phone-description-text]="!isTablet"
                                            [class.tablet-description-text]="isTablet"
                                            [class.unselected]="selectedTab != 1 || expandRecent == false"
                                            [class.selected]="selectedTab == 1"></label>
                                    </StackLayout>
                                </GridLayout>
                                <label [text]="'ion-chevron-down' | fonticon" class="ion description-text"
                                    horizontalAlignment="right" *ngIf='expandRecent'></label>
                                <label [text]="'ion-chevron-up' | fonticon" class="ion" horizontalAlignment="right"
                                    *ngIf='!expandRecent'></label>
                            </StackLayout>
                            <StackLayout [visibility]="expandRecent ? 'visible' : 'collapsed'">
                                <ListView [items]="synchedWorkRequests" [class.phone-tile]="!isTablet"
                                    [class.tablet-tile]="isTablet">
                                    <ng-template let-i="index" let-item="item">
                                        <GridLayout columns="* * 3* auto" class="header p-l-10" [height]="listItem"
                                            [class.phone-container-stack]="!isTablet"
                                            [class.tablet-container-stack]="isTablet">
                                            <label col="0" [text]="item.date" [class.phone-request-header]="!isTablet"
                                                [class.tablet-request-header]="isTablet" textWrap="true"
                                                verticalAlignment="middle"></label>
                                            <label col="1" [text]="item.refNumber" color="#002776"
                                                [class.phone-request-header]="!isTablet"
                                                [class.tablet-request-header]="isTablet" textWrap="true"
                                                horizontalAlignment="center" verticalAlignment="middle"></label>
                                            <label col="2" [text]="item.description"
                                                [class.phone-request-header]="!isTablet"
                                                [class.tablet-request-header]="isTablet" textWrap="true"
                                                horizontalAlignment="left" verticalAlignment="middle"></label>
                                            <label col="3" *ngIf='item.isSynched' color="green"
                                                [text]="'ion-android-sync' | fonticon" class="ion m-r-10"
                                                [class.phone-request-header]="!isTablet" horizontalAlignment="center"
                                                [class.tablet-request-header]="isTablet" textWrap="true"
                                                verticalAlignment="middle"></label>
                                            <label col="3" *ngIf='!item.isSynched' color="red"
                                                [text]="'ion-android-sync' | fonticon" class="ion m-r-10"
                                                [class.phone-request-header]="!isTablet" horizontalAlignment="center"
                                                [class.tablet-request-header]="isTablet" textWrap="true"
                                                verticalAlignment="middle"></label>
                                        </GridLayout>
                                    </ng-template>
                                </ListView>
                            </StackLayout>
                            <StackLayout [visibility]="expandApproval ? 'visible' : 'collapsed'">
                                <ListView [items]="unsynchedWorkRequests" [class.phone-tile]="!isTablet"
                                    [class.tablet-tile]="isTablet">
                                    <ng-template let-i="index" let-item="item">
                                        <GridLayout columns="* * 3* auto" class="header p-l-10"
                                            [class.phone-container-stack]="!isTablet"
                                            [class.tablet-container-stack]="isTablet">
                                            <label col="0" [text]="item.date" [class.phone-request-header]="!isTablet"
                                                [class.tablet-request-header]="isTablet" textWrap="true"
                                                verticalAlignment="middle"></label>
                                            <label col="1" [text]="item.refNumber" color="#002776"
                                                [class.phone-request-header]="!isTablet"
                                                [class.tablet-request-header]="isTablet" textWrap="true"
                                                horizontalAlignment="center" verticalAlignment="middle"></label>
                                            <label col="2" [text]="item.description"
                                                [class.phone-request-header]="!isTablet"
                                                [class.tablet-request-header]="isTablet" textWrap="true"
                                                horizontalAlignment="left" verticalAlignment="middle"></label>
                                            <label col="3" *ngIf='item.isSynched' color="green"
                                                [text]="'ion-android-sync' | fonticon" class="ion m-r-10"
                                                [class.phone-request-header]="!isTablet" horizontalAlignment="center"
                                                [class.tablet-request-header]="isTablet" textWrap="true"
                                                verticalAlignment="middle"></label>
                                            <label col="3" *ngIf='!item.isSynched' color="red"
                                                [text]="'ion-android-sync' | fonticon" class="ion m-r-10"
                                                [class.phone-request-header]="!isTablet" horizontalAlignment="center"
                                                [class.tablet-request-header]="isTablet" textWrap="true"
                                                verticalAlignment="middle"></label>
                                        </GridLayout>
                                    </ng-template>
                                </ListView>
                            </StackLayout>
                        </StackLayout>
                    </StackLayout>
                </StackLayout>

                <StackLayout *ngIf="!isCoal">
                    <StackLayout class="content bottom-separator">
                        <GridLayout rows="* auto" columns="auto 4* *" class="m-5" [class.tablet-content-grid]="isTablet"
                            [class.phone-content-grid]="!isTablet">
                            <StackLayout row="0" rowSpan="2" col="0" class="icon-stack"
                                [class.tablet-icon-stack]="isTablet" [class.phone-icon-stack]="!isTablet">
                                <label color="white" [text]="'ion-wrench' | fonticon" class="ion"
                                    [class.phone-icon]="!isTablet" [class.tablet-icon]="isTablet"
                                    horizontalAlignment="center"></label>
                            </StackLayout>
                            <label [class.phone-header-text]="!isTablet" [class.tablet-header-text]="isTablet"
                                verticalAlignment="top" class="m-l-5 header" text=" Requests" row="0" col="1"
                                (tap)="onItemTap( 0 )"></label>
                            <label [class.phone-description-text]="!isTablet" [class.tablet-description-text]="isTablet"
                                class="description-text m-l-5" text="Create or View Requests" row="1"
                                col="1"></label>
                            <GridLayout row="0" rowSpan="2" col="2" columns="* *">
                                <StackLayout col="0" *ngIf="isTablet" (tap)="onItemTap( 0 )">
                                    <label [class.phone-icon]="!isTablet" [class.tablet-icon]="isTablet"
                                        horizontalAlignment="center" class="ion header"
                                        [text]="'ion-android-search' | fonticon"></label>
                                </StackLayout>
                                <StackLayout col="1" (tap)="onAddTap( 0 )">
                                    <label [class.phone-icon]="!isTablet" [class.tablet-icon]="isTablet"
                                        horizontalAlignment="center" class="ion header"
                                        [text]="'ion-android-add' | fonticon"></label>
                                </StackLayout>
                            </GridLayout>
                        </GridLayout>
                        <StackLayout>
                            <StackLayout class="m-x-5 m-t-10">
                                <GridLayout columns="* *" width="50%" horizontalAlignment="left">
                                    <StackLayout col="0">
                                        <label text="Most recent" horizontalAlignment="left" (tap)="onRecentTap()"
                                            [class.phone-description-text]="!isTablet"
                                            [class.tablet-description-text]="isTablet"
                                            [class.unselected]="selectedTab != 1 || expandRecent == false"
                                            [class.selected]="selectedTab == 1"></label>
                                    </StackLayout>
                                    <StackLayout col="1" orientation="horizontal">
                                        <label text="Approval" horizontalAlignment="left" (tap)="onApprovalTap()"
                                            [class.phone-description-text]="!isTablet"
                                            [class.tablet-description-text]="isTablet"
                                            [class.unselected]="selectedTab != 2 || expandApproval == false"
                                            [class.selected]="selectedTab == 2"></label>
                                        <label class="count-number" [text]='" (" + synchCount + ")"'
                                            [class.phone-description-text]="!isTablet"
                                            [class.tablet-description-text]="isTablet"></label>
                                    </StackLayout>
                                </GridLayout>
                                <label [text]="'ion-chevron-down' | fonticon" class="ion description-text"
                                    horizontalAlignment="right" *ngIf='expandRecent'></label>
                                <label [text]="'ion-chevron-up' | fonticon" class="ion description-text"
                                    horizontalAlignment="right" *ngIf='!expandRecent'></label>
                            </StackLayout>
                            <StackLayout [visibility]="expandRecent ? 'visible' : 'collapsed'">
                                <ListView [items]="synchedWorkRequests" [height]='requestCount'>
                                    <ng-template let-i="index" let-item="item">
                                        <GridLayout columns="* * 3* auto" class="header p-l-10" [height]='listItem'
                                            [class.phone-container-stack]="!isTablet"
                                            [class.tablet-container-stack]="isTablet">
                                            <label col="0" [text]="item.date" [class.phone-request-header]="!isTablet"
                                                [class.tablet-request-header]="isTablet" textWrap="true"
                                                verticalAlignment="middle"></label>
                                            <label col="1" [text]="item.refNumber" color="#002776"
                                                [class.phone-request-header]="!isTablet"
                                                [class.tablet-request-header]="isTablet" textWrap="true"
                                                horizontalAlignment="center" verticalAlignment="middle"></label>
                                            <label col="2" [text]="item.description"
                                                [class.phone-request-header]="!isTablet"
                                                [class.tablet-request-header]="isTablet" textWrap="true"
                                                horizontalAlignment="left" verticalAlignment="middle"></label>
                                            <label col="3" *ngIf='item.isSynched' color="green"
                                                [text]="'ion-android-sync' | fonticon" class="ion m-r-10"
                                                [class.phone-request-header]="!isTablet" horizontalAlignment="center"
                                                [class.tablet-request-header]="isTablet" textWrap="true"
                                                verticalAlignment="middle"></label>
                                            <label col="3" *ngIf='!item.isSynched' color="red"
                                                [text]="'ion-android-sync' | fonticon" class="ion m-r-10"
                                                [class.phone-request-header]="!isTablet" horizontalAlignment="center"
                                                [class.tablet-request-header]="isTablet" textWrap="true"
                                                verticalAlignment="middle"></label>
                                        </GridLayout>
                                    </ng-template>
                                </ListView>
                            </StackLayout>
                            <StackLayout [visibility]="expandApproval ? 'visible' : 'collapsed'">
                                <ListView [items]="unsynchedWorkRequests" [height]='unsynchRequestCount'>
                                    <ng-template let-i="index" let-item="item">
                                        <GridLayout columns="* * 3* auto" class="header p-l-10" [height]='listItem'
                                            [class.phone-container-stack]="!isTablet"
                                            [class.tablet-container-stack]="isTablet">
                                            <label col="0" [text]="item.date" [class.phone-request-header]="!isTablet"
                                                [class.tablet-request-header]="isTablet" textWrap="true"
                                                verticalAlignment="middle"></label>
                                            <label col="1" [text]="item.refNumber" color="#002776"
                                                [class.phone-request-header]="!isTablet"
                                                [class.tablet-request-header]="isTablet" textWrap="true"
                                                horizontalAlignment="center" verticalAlignment="middle"></label>
                                            <label col="2" [text]="item.description"
                                                [class.phone-request-header]="!isTablet"
                                                [class.tablet-request-header]="isTablet" textWrap="true"
                                                horizontalAlignment="left" verticalAlignment="middle"></label>
                                            <label col="3" *ngIf='item.isSynched' color="green"
                                                [text]="'ion-android-sync' | fonticon" class="ion m-r-10"
                                                [class.phone-request-header]="!isTablet" horizontalAlignment="center"
                                                [class.tablet-request-header]="isTablet" textWrap="true"
                                                verticalAlignment="middle"></label>
                                            <label col="3" *ngIf='!item.isSynched' color="red"
                                                [text]="'ion-android-sync' | fonticon" class="ion m-r-10"
                                                [class.phone-request-header]="!isTablet" horizontalAlignment="center"
                                                [class.tablet-request-header]="isTablet" textWrap="true"
                                                verticalAlignment="middle"></label>
                                        </GridLayout>
                                    </ng-template>
                                </ListView>
                            </StackLayout>
                        </StackLayout>
                    </StackLayout>

                    <StackLayout class="content bottom-separator">
                        <GridLayout rows="* auto" columns="auto 4* *" class="m-5" [class.tablet-content-grid]="isTablet"
                            [class.phone-content-grid]="!isTablet">
                            <StackLayout row="0" rowSpan="2" col="0" class="icon-stack"
                                [class.tablet-icon-stack]="isTablet" [class.phone-icon-stack]="!isTablet">
                                <label color="white" [text]="'ion-android-clipboard' | fonticon" class="ion"
                                    [class.phone-icon]="!isTablet" [class.tablet-icon]="isTablet"
                                    horizontalAlignment="center"></label>
                            </StackLayout>
                            <label [class.phone-header-text]="!isTablet" [class.tablet-header-text]="isTablet"
                                class="m-l-5 header" text="Work Orders" row="0" col="1" verticalAlignment="top"
                                (tap)="onItemTap( 1 )"></label>
                            <label [class.phone-description-text]="!isTablet" [class.tablet-description-text]="isTablet"
                                class="description-text m-l-5" text=" Work Work Orders / Job Cards" row="1"
                                col="1"></label>
                            <GridLayout row="0" rowSpan="2" col="2" columns="* *">
                                <StackLayout col="0" *ngIf="isTablet" (tap)="onItemTap( 1 )">
                                    <label [class.phone-icon]="!isTablet" [class.tablet-icon]="isTablet"
                                        horizontalAlignment="center" class="ion header"
                                        [text]="'ion-android-search' | fonticon"></label>
                                </StackLayout>
                                <StackLayout col="1">
                                    <label [class.phone-icon]="!isTablet" [class.tablet-icon]="isTablet"
                                        horizontalAlignment="center" class="ion header"
                                        [text]="'ion-android-add' | fonticon"></label>
                                </StackLayout>
                            </GridLayout>
                        </GridLayout>
                        <StackLayout>
                            <StackLayout class="m-x-5 m-t-10">
                                <GridLayout columns="* * *" width="100%" horizontalAlignment="left">
                                    <StackLayout col="0" orientation="horizontal">
                                        <label text="Today" horizontalAlignment="left" class="unselected"
                                            [class.phone-description-text]="!isTablet"
                                            [class.tablet-description-text]="isTablet"></label>
                                        <label class="count-number" horizontalAlignment="left" text=" (2)"
                                            [class.phone-description-text]="!isTablet"
                                            [class.tablet-description-text]="isTablet"></label>
                                    </StackLayout>
                                    <StackLayout col="1" orientation="horizontal">
                                        <label text="Tomorrow" horizontalAlignment="left" class="unselected"
                                            [class.phone-description-text]="!isTablet"
                                            [class.tablet-description-text]="isTablet"></label>
                                        <label class="count-number" horizontalAlignment="left" text=" (1)"
                                            [class.phone-description-text]="!isTablet"
                                            [class.tablet-description-text]="isTablet"></label>
                                    </StackLayout>
                                    <StackLayout col="2" orientation="horizontal">
                                        <label text="Upcoming" horizontalAlignment="left" class="unselected"
                                            [class.phone-description-text]="!isTablet"
                                            [class.tablet-description-text]="isTablet"></label>
                                        <label class="count-number" horizontalAlignment="left" text=" (2)"
                                            [class.phone-description-text]="!isTablet"
                                            [class.tablet-description-text]="isTablet"></label>
                                    </StackLayout>
                                </GridLayout>
                                <label [text]="'ion-chevron-down' | fonticon" class="ion description-text"
                                    horizontalAlignment="right" *ngIf="expandRecent"></label>
                                <label [text]="'ion-chevron-up' | fonticon" class="ion description-text"
                                    horizontalAlignment="right" *ngIf="!expandRecent"></label>
                            </StackLayout>
                            <StackLayout visibility="collapsed">
                                <ListView [items]="synchedWorkRequests" height="100%">
                                    <ng-template let-i="index" let-item="item">
                                        <GridLayout columns="* * 3* auto" class="bottom-separator header p-l-10"
                                            [class.phone-container-stack]="!isTablet"
                                            [class.tablet-container-stack]="isTablet">
                                            <label col="0" [text]="item.date" [class.phone-request-header]="!isTablet"
                                                [class.tablet-request-header]="isTablet" textWrap="true"
                                                verticalAlignment="middle"></label>
                                            <label col="1" [text]="item.refNumber" color="#002776"
                                                [class.phone-request-header]="!isTablet"
                                                [class.tablet-request-header]="isTablet" textWrap="true"
                                                horizontalAlignment="center" verticalAlignment="middle"></label>
                                            <label col="2" [text]="item.description"
                                                [class.phone-request-header]="!isTablet"
                                                [class.tablet-request-header]="isTablet" textWrap="true"
                                                horizontalAlignment="left" verticalAlignment="middle"></label>
                                            <label col="3" *ngIf='item.isSynched' color="green"
                                                [text]="'ion-android-sync' | fonticon" class="ion m-r-10"
                                                [class.phone-request-header]="!isTablet" horizontalAlignment="center"
                                                [class.tablet-request-header]="isTablet" textWrap="true"
                                                verticalAlignment="middle"></label>
                                            <label col="3" *ngIf='!item.isSynched' color="red"
                                                [text]="'ion-android-sync' | fonticon" class="ion m-r-10"
                                                [class.phone-request-header]="!isTablet" horizontalAlignment="center"
                                                [class.tablet-request-header]="isTablet" textWrap="true"
                                                verticalAlignment="middle"></label>
                                        </GridLayout>
                                    </ng-template>
                                </ListView>
                            </StackLayout>
                        </StackLayout>
                    </StackLayout>

                    <StackLayout class="content bottom-separator">
                        <GridLayout rows="* auto" columns="auto 4* *" class="m-5" [class.tablet-content-grid]="isTablet"
                            [class.phone-content-grid]="!isTablet">
                            <StackLayout row="0" rowSpan="2" col="0" class="icon-stack"
                                [class.tablet-icon-stack]="isTablet" [class.phone-icon-stack]="!isTablet">
                                <label color="white" [text]="'ion-android-alarm-clock' | fonticon" class="ion"
                                    [class.phone-icon]="!isTablet" [class.tablet-icon]="isTablet"
                                    horizontalAlignment="center"></label>
                            </StackLayout>
                            <label [class.phone-header-text]="!isTablet" [class.tablet-header-text]="isTablet"
                                class="m-l-5 header" text="My Actions" row="0" col="1" verticalAlignment="top"
                                (tap)="onItemTap( 0 )"></label>
                            <label [class.phone-description-text]="!isTablet" [class.tablet-description-text]="isTablet"
                                class="description-text m-l-5" text="Actions Created or Assigned" row="1"
                                col="1"></label>
                            <GridLayout row="0" rowSpan="2" col="2" columns="* *">
                                <StackLayout col="0" *ngIf="isTablet" (tap)="onItemTap( 0 )">
                                    <label [class.phone-icon]="!isTablet" [class.tablet-icon]="isTablet"
                                        horizontalAlignment="center" class="ion header"
                                        [text]="'ion-android-search' | fonticon"></label>
                                </StackLayout>
                                <StackLayout col="1" (tap)="onAddTap( 0 )">
                                    <label [class.phone-icon]="!isTablet" [class.tablet-icon]="isTablet"
                                        horizontalAlignment="center" class="ion header"
                                        [text]="'ion-android-add' | fonticon"></label>
                                </StackLayout>
                            </GridLayout>
                        </GridLayout>
                        <StackLayout>
                            <StackLayout class="m-x-5 m-t-10">
                                <GridLayout columns="* * *" width="100%" horizontalAlignment="left">
                                    <StackLayout col="0" orientation="horizontal">
                                        <label text="Due Today" horizontalAlignment="left" class="unselected"
                                            [class.phone-description-text]="!isTablet"
                                            [class.tablet-description-text]="isTablet"></label>
                                        <label class="count-number" horizontalAlignment="left" text=" (2)"
                                            [class.phone-description-text]="!isTablet"
                                            [class.tablet-description-text]="isTablet"></label>
                                    </StackLayout>
                                    <StackLayout col="1" orientation="horizontal">
                                        <label text="Upcoming" horizontalAlignment="left" class="unselected"
                                            [class.phone-description-text]="!isTablet"
                                            [class.tablet-description-text]="isTablet"></label>
                                        <label class="count-number" horizontalAlignment="left" text=" (1)"
                                            [class.phone-description-text]="!isTablet"
                                            [class.tablet-description-text]="isTablet"></label>
                                    </StackLayout>
                                    <StackLayout col="2" orientation="horizontal">
                                        <label text="Overdue" horizontalAlignment="left" class="unselected"
                                            [class.phone-description-text]="!isTablet"
                                            [class.tablet-description-text]="isTablet"></label>
                                        <label class="count-number" horizontalAlignment="left" text=" (2)"
                                            [class.phone-description-text]="!isTablet"
                                            [class.tablet-description-text]="isTablet"></label>
                                    </StackLayout>
                                </GridLayout>
                                <label [text]="'ion-chevron-down' | fonticon" class="ion description-text"
                                    horizontalAlignment="right" *ngIf="expandRecent"></label>
                                <label [text]="'ion-chevron-up' | fonticon" class="ion description-text"
                                    horizontalAlignment="right" *ngIf="!expandRecent"></label>
                            </StackLayout>
                        </StackLayout>
                    </StackLayout>

                    <StackLayout class="content bottom-separator">
                        <GridLayout rows="* auto" columns="auto 4* *" class="m-5" [class.tablet-content-grid]="isTablet"
                            [class.phone-content-grid]="!isTablet">
                            <StackLayout row="0" rowSpan="2" col="0" class="icon-stack"
                                [class.tablet-icon-stack]="isTablet" [class.phone-icon-stack]="!isTablet">
                                <label color="white" [text]="'fa-check' | fonticon" class="fa"
                                    [class.phone-icon]="!isTablet" [class.tablet-icon]="isTablet"
                                    horizontalAlignment="center"></label>
                            </StackLayout>
                            <label [class.phone-header-text]="!isTablet" [class.tablet-header-text]="isTablet"
                                class="m-l-5 header" text="Checklists" row="0" col="1" verticalAlignment="top"
                                (tap)="onItemTap( 0 )"></label>
                            <label [class.phone-description-text]="!isTablet" [class.tablet-description-text]="isTablet"
                                class="description-text m-l-5" text="Complete Checklist" row="1" col="1"></label>
                            <GridLayout row="0" rowSpan="2" col="2" columns="* *">
                                <StackLayout col="0" *ngIf="isTablet" (tap)="onItemTap( 0 )">
                                    <label [class.phone-icon]="!isTablet" [class.tablet-icon]="isTablet"
                                        horizontalAlignment="center" class="ion header"
                                        [text]="'ion-android-search' | fonticon"></label>
                                </StackLayout>
                                <StackLayout col="1" (tap)="onAddTap( 0 )">
                                    <label [class.phone-icon]="!isTablet" [class.tablet-icon]="isTablet"
                                        horizontalAlignment="center" class="ion header"
                                        [text]="'ion-android-add' | fonticon"></label>
                                </StackLayout>
                            </GridLayout>
                        </GridLayout>
                        <StackLayout>
                            <StackLayout class="m-x-5 m-t-10">
                                <GridLayout columns="* * *" width="70%" horizontalAlignment="left">
                                    <StackLayout col="0" orientation="horizontal">
                                        <label text="" horizontalAlignment="left" class="unselected"></label>
                                    </StackLayout>
                                </GridLayout>
                                <label [text]="'ion-chevron-down' | fonticon" class="ion description-text"
                                    horizontalAlignment="right" *ngIf="expandRecent"></label>
                                <label [text]="'ion-chevron-up' | fonticon" class="ion description-text"
                                    horizontalAlignment="right" *ngIf="!expandRecent"></label>
                            </StackLayout>
                        </StackLayout>
                    </StackLayout>
                </StackLayout>
            </ScrollView>
        </StackLayout>

        
        <GridLayout row="2" *ngIf="isTablet" verticalAlignment="bottom" columns="* * *" class="tab-grid p-t-10">
            <StackLayout col="0" (tap)="onTabItemTap(0)">
                <label [text]="'fa-user' | fonticon" class="fa tab-icon h2" horizontalAlignment="center"></label>
                <label text="Profile" class="tab-text"></label>
            </StackLayout>
            <StackLayout col="1" (tap)="customSheetTap()">
                <label [text]="'fa-plus' | fonticon" horizontalAlignment="center" class="fa tab-icon h2"></label>
                <label text="" class="tab-text"></label>
            </StackLayout>
            <StackLayout col="2" (tap)="onTabItemTap(6)">
                <label [text]="'fa-bell' | fonticon" horizontalAlignment="center" class="fa tab-icon h2"></label>
                <label text="Alerts" class="tab-text"></label>
            </StackLayout>
        </GridLayout>

        
        <GridLayout row="2" *ngIf="!isTablet" verticalAlignment="bottom" columns="* * *" class="tab-grid p-t-15 p-b-10">
            <StackLayout col="0" (tap)="onTabItemTap(0)">
                <label [text]="'fa-user' | fonticon" class="fa tab-icon h2" horizontalAlignment="center"></label>
            </StackLayout>
            <StackLayout col="1" (tap)="customSheetTap($event)">
                <label [text]="'fa-plus' | fonticon" horizontalAlignment="center" class="fa tab-icon h2"></label>
            </StackLayout>
            <StackLayout col="2" (tap)="onTabItemTap(2)">
                <label [text]="'fa-bell' | fonticon" horizontalAlignment="center" class="fa tab-icon h2"></label>
            </StackLayout>
        </GridLayout>
    </GridLayout>
</RadSideDrawer>

**Comment by manijak** [comment]
That's a lot of code :) I ment a photo or a video of the issue? Is the Carousel fullscreen when this happens?
