### ISSUE TITLE
Wrapping nativescript-image for image preloading

### ISSUE THREAD

**Issue by markosole** [manijak/nativescript-carousel#122]
Hi, I have tried to wrap  xmlns:img="nativescript-image" plugin inside itemTemplate for image preloading feature but it does not work.

Code I am using:
 
    <ns:Carousel.itemTemplate>
     <ns:CarouselItem odrediste="{{ odrediste }}" class="carusel-item" tap="slajderTap" 
     backgroundColor="#F2F2F2" verticalAlignment="middle">  
                     <img:Img src="{{ putanja_slika + '' + slika_image }}"/>                            
              </ns:CarouselItem>
     </ns:Carousel.itemTemplate>

Is there a way to use any PlaceHolder until image is loaded from external source? Sorry this is more like feature request but problem in other hand.

**Comment by manijak** [comment]
Pozdrav Marko!
I presume that the `xmlns:img="nativescript-image"` is a plugin? From my experiance you must set height/width on either the Image itself or the Carousel. That was the case with most image plugins out there, only the stock Image element did not have this issue.

**Comment by markosole** [comment]
Pozdrav Nenade (predpostavljam)!
Yep you are right, why I did not try that before!? It works now, plugin is great! iOS test takes place tomorrow.
btw: samo mi nemoj još reći da se i znamo?! :D

**Comment by manijak** [comment]
Ime je Nedim ;) i mislim da se ne poznajemo. Pozdrav!
