### ISSUE TITLE
Carousel items disappear on iOS iPhone Xs (Vue demo)

### ISSUE THREAD

**Issue by chriskeehealth** [manijak/nativescript-carousel#124]
I'm running demo-vue on iOS - iPhone Xs simulator (Nativescript v6.0.1)
I've noticed when the app loses focus and opens back, the carousel items disappear.  Another oddity is, if you rotate the screen, you can get the carousel items to reappear.  I have run the same app on iPhone 6s simulator with no issues.

![carousel](https://user-images.githubusercontent.com/30606079/63305681-6b7d1100-c2ad-11e9-90cd-30ffa9898672.gif)

**Comment by manijak** [comment]
I have not seen this using ns core, could be a vue issue. Could you please try out the `dev` branch of the Pod?

Just open the podfile located under `nativescript-carousel\platforms\ios\podfile` and change it to:
`pod 'DKCarouselView', :git => 'https://github.com/manijak/DKCarouselView', :branch => 'dev'`

Clean the app platforms folder & rebuild. Let me know if this fixes the issue. Thanks.

**Comment by EmielH** [comment]
I'm having the same issue, only on iOS, when changing the orientation to face up or face down. Rotating to landscape brings the items back. I'm not sure how to debug this.

I'm using NativeScript 6.0.2 with Angular and nativescript-carousel 6.1.0.

I don't have issues when the app loses focus, so if my problem actually is a different issue I'd be happy to create one with any additional information that you need.

**Comment by manijak** [comment]
@EmielH Could you try the above workaround and let me know if that helps?

**Comment by chriskeehealth** [comment]
@manijak That workaround worked and I noticed too that the 6.1.1 version makes use of the updated pod.  Thank you for your help with this.

**Comment by EmielH** [comment]
@chriskeehealth Just to let you know: version 6.1.1 solves my problem as well.
