### ISSUE TITLE
Changing font Size dynamically

### ISSUE THREAD

**Issue by MariSpr** [manijak/nativescript-carousel#125]
Hey there, first, thanks for this great piece of plugin! :-)

I was trying to change the font-Size of the Label which is inside the Caroussel by picking up the element with getViewById.

It works for the first element, but not for the subsequent ones, probably because the ID is unique, but I was wondering if I could apply the same ID to the next (or all dynamically created) caroussels??

I am working with Vanilla and using observableArrays for feeding the caroussel.

Thanks in advance!

**Comment by manijak** [comment]
I recomend using the `loaded` event of the `CarouselItem`:
```xml
<ns:CarouselItem loaded="onLoadedCarouselItem">
...
</ns:CarouselItem>
```
Then in your code:

```js
export function onLoadedCarouselItem(args: EventData) {
    const carouselItem:any = args.object;
    const someGridLayout = <GridLayout>carouselItem.getViewById('cardGridId');
    ...
};
```

**Comment by MariSpr** [comment]
Hi manijak,

thanks for your quick answer! I tried this but it works only for the first item. When I swipe to the next one, the changes don't apply anymore. 

`function carouselLoaded(args) {
    carouselItem = args.object;
    myOutputText = carouselItem.getViewById('output');
    myOutputText.fontSize = 32;
    myOutputText.className = "klein";
}`

I also tried to apply the change on every changeEvent but it did not work either. Wierdly it will declare to have the new font size if I trace it, but it still shows the wrong size.

`function myChangeEvent(args) {
    myOutputText.className = "klein";
    myOutputText.fontSize = 32;
    alert(myOutputText.fontSize);
}`

any other ideas?! 

Thanks in advance! Mariana

**Comment by manijak** [comment]
Sorry for the late reply. Strange that it doesn't work for you. I have a similar function in my app and it works fine when using the `loaded` event. Just so there is no confusion, the `loaded` event needs to be on the `CarouselItem` not the `Carousel`. 

You can also try and set the font size via css-class either in code or dynamic via xml in the template.

**Comment by MariSpr** [comment]
Hey, thanks for your answer, I changed the loaded event to the CarouselItem and now it works, amazing!! :-)

Thanks again and havea nice weeked!
