### ISSUE TITLE
Dependency were found, but they required a higher minimum deployment target.

### ISSUE THREAD

**Issue by Nurgunkalol** [manijak/nativescript-carousel#127]
Error: Specs satisfying the `DKCarouselView (from `https://github.com/manijak/DKCarouselView`)` dependency were found, but they required a higher minimum deployment target.

```
..
  "tns-android": {
      "version": "4.2.0"
    },
    "tns-ios": {
      "version": "4.2.0"
    }
...
    "nativescript-carousel": "^3.0.2"
```

**Comment by manijak** [comment]
Sorry but older versions are not supported anymore.

**Comment by manijak** [comment]
Let me just explain. The carousel plugin you are using is very old, but the pod that the plugin depends on is very new. So there lies the issue. What you can do, if you still want to keep `3.0.2` of the carousel is to update the Pod file in the plugin to download the correct version.

Just update the pod file to the following:
`pod 'DKCarouselView', :git => 'https://github.com/manijak/DKCarouselView', :tag => '2.4.13'
`
