### ISSUE TITLE
Height problem

### ISSUE THREAD

**Issue by Lelelo1** [manijak/nativescript-carousel#128]
I have a grid layout that contains an image and label on top. But I can't make the grid layout containing the image to assume the height of the Carousel (in blue):

![height](https://user-images.githubusercontent.com/42244983/64370183-35b28900-d01e-11e9-9172-e8dff5c11e70.png)

Setting no height on the gridLayout or the image I get this:

![nonGIvenHeight](https://user-images.githubusercontent.com/42244983/64370713-4b747e00-d01f-11e9-87a7-8dc79f0bb6f3.png)

And using StackLayout I get the same results.

Shoulden't create the Carousel **indicator overlap the content** - and adjust the size of it's content?

Additionally, setting the carouselItem to `backgroundColor=new Color("green")` - the image is no longer displayed - only showing the blue color of the Carousel.

Here is the image - where `src` is local: `res://myimage`.

```
    const image = new Image();
    image.src = src;
    image.stretch = "fill"
```

and I create Carousel like so:

```
carousel(gridLayouts: GridLayout[]) {
    const carousel = new Carousel();
    carousel.backgroundColor = new Color('blue');
    gridLayouts.forEach(element => {
        const carouselItem = new CarouselItem();
        // carouselItem.backgroundColor = new Color("green");
        carouselItem.addChild(element);
        carousel.addChild(carouselItem);
    });
    return carousel;
}
```

And the carousel is then added to a StackLayout.

**Comment by manijak** [comment]
Not easy to know without the xml. but try and wrap the `Carousel` in a `GridLayout`

**Comment by Lelelo1** [comment]
It did not work.
I will try reproduce it in a vanilla ts project. This is in a react-nativescript project. What I have done should be the same thing as adding everything in the code behind file though.

**Comment by Lelelo1** [comment]
When scrolling I noticed much of the image was underneath ActionBar:

![hieghtNoActionBar](https://user-images.githubusercontent.com/42244983/64604970-7534f880-d3c3-11e9-9b01-313006a7d7eb.png)

The blue area still there - Which I suspect is the status bar area - as I have set the margin and padding of everything to 0.

Setting `verticalAlignment = "bottom"` on the CarouselItem. The Color shifts to pink - which is the color I set for the gridLayout container the image and the label - just for testing. But verticalAlignment on the image and label did not push the content down.

**Comment by Lelelo1** [comment]
Realising the Carousel extends a GridLayout it is in fact as simple as `carousel.iosOverflowSafeArea = false;`

**Comment by manijak** [comment]
Thanks for the feedback on this issue. All layouts in nativescript are by default `iosOverflowSafeArea = true` and since Carousel extends GirdLayout the effect is applied here too. 

But from reading your conclusion, you also had to set `iosOverflowSafeArea = false` to the GridLayout innside the CarouselItem as well?

**Comment by Lelelo1** [comment]
> Thanks for the feedback on this issue. All layouts in nativescript are by default `iosOverflowSafeArea = true` and since Carousel extends GirdLayout the effect is applied here too.
> 
> But from reading your conclusion, you also had to set `iosOverflowSafeArea = false` to the GridLayout innside the CarouselItem as well?

No it was only needed on the outer GridLayout - the Carousel.
