### ISSUE TITLE
Indicator Offset doesn't work on Android

### ISSUE THREAD

**Issue by nerdrun** [manijak/nativescript-carousel#129]
Hello @manijak .
While I'm using your amazing plugin I've found the indicator offset doesn't work.
I've tried `indicatorOffset="0,-10"` as inline-tag and also programatic way like `myCarousel.nativeView.indicatorOffset  = '-10,0'`.

Ah, I set debug mode true to see properties are set up well, but wasn't shown up only offset in the console.

Is this a new bug or did i make some mistake?

====== EDIT ======
In your documentation It said **indicatorAlignment Sets the pager-indicator alignment. Choose between top or bottom. Default is bottom.**
but `indicatorAlignment="bottom"` doesn't work properly so that I adjusted the layout using FlexboxLayout

**Comment by manijak** [comment]
Don't know what platform you are on, but `indicatorAlignment` is only for Android. `bottom` is default and it works, so I did not understand what you ment by "doesn't work properly". :)

**Comment by nerdrun** [comment]
Thanks for the fast response, @manijak !
I'm so sorry that I didn't specified my developing environment.

### Environement
**Testing device info**
* Model: Galaxy A8 Star
* Android Version: 9

**Developing device info**
* TNS version: 6.0.3
* Framework: Nativescript-vue
* Tool: Nativescript Sidekick

And this is my test code to explain what I meant.

Vue template
```
<template>
  <Page class="page">
    <ActionBar class="action-bar">
      <Label class="action-bar-title" text="Home"></Label>
    </ActionBar>
    <StackLayout class="carousel-w">
      <Carousel
        ref="myCarousel"
        class="carousel"
        android:indicatorAnimation="slide"
        indicatorAlignment="bottom"
        indicatorOffset="-50, -100"
        showIndicator="true">
        <CarouselItem>
          <FlexboxLayout justifyContent="center" alignItems="center">
            <Label text="Test Label 1" />
          </FlexboxLayout>
        </CarouselItem>
        <CarouselItem>
          <FlexboxLayout justifyContent="center" alignItems="center">
            <Label text="Test Label 2" />
          </FlexboxLayout>
        </CarouselItem>
      </Carousel>
    </StackLayout>
  </Page>
</template>
```

Javascript
```
export default {
  data() {
    return {
      msg: 'Thank you manijak!'
    }
  },
  methods: {
    onLoaded() {
      console.log('Hello')
      console.log(this.$refs.myCarousel.nativeView.indicatorOffset) // It shows "-50,-100" on the console
      // this.$refs.myCarousel.nativeView.indicatorOffset = '20, 30' 
      console.log(this.$refs.myCarousel.nativeView.indicatorOffset) // It shows "20,30" on the console but not affect still...
    }
  }
}
```

CSS
```
<style scoped lang="scss">
.carousel-w {
  width: 100%;
  height: 300;
  background-color: rgba(102, 102, 102, 0.8);
  .carousel {
    width: 100%;
    height: 80%;
  }
}
</style>
```

First of all,
In your documentation, If Carousel sets ```indicatorAlignment``` the indicator will be placed on the center below, but it doesn't work properly.

And second, ```indicatorOffset``` can points (x,y) to move the indicator but not working neither.

The result as image below :

[![IMG-9037.jpg](https://i.postimg.cc/W3YLn88L/IMG-9037.jpg)](https://postimg.cc/sQWNfpbw)

**Comment by manijak** [comment]
You should always wrap the `Carousel` in a `GridLayout`
```xml
<GridLayout>
    <Carousel>
        ....
    </Carousel>
</GridLayout>
```

**Comment by nerdrun** [comment]
Oh! In my product code, Carousel is wrapped by FlexboxLayout.
I'll try it as you said.

Thank you @manijak

**Comment by narender56** [comment]
Has it ever worked? I spent three hours attempting to make it work using Grid, Flex, or any other layout, but it DOESN'T work

**Comment by narender56** [comment]
Except `indicatorColor` nothing related to Indicators work. radius, padding, or offset doesn't work at all.

Trying in NS7 & Angular with "@nstudio/nativescript-carousel": "^8.0.3"

**Comment by narender56** [comment]
Is there any class, I can target the indicators and apply some css

**Comment by manijak** [comment]
@narender56 This version of the plugin is not maintained anymore. The crew over at NSStudio has taken over the work: https://github.com/nstudio/nativescript-plugins/tree/main/packages/nativescript-carousel

**Comment by narender56** [comment]
Yup, I'm having issues with NSStudio plugin `@nstudio/nativescript-carousel` itself
