### ISSUE TITLE
Carousel Page Indicator position?

### ISSUE THREAD

**Issue by dlucidone** [manijak/nativescript-carousel#13]
The Carousel items pager seems to be at left corner. Not able to fix it to center of all elements.
![screen shot 2017-02-28 at 9 56 04 pm](https://cloud.githubusercontent.com/assets/9256365/23414086/bf479770-fe00-11e6-9f28-6a3f00d6b476.png)

**Comment by manijak** [comment]
The screenshot seems to be broken...
Did you try and wrap the Carousel component innside a `<GridLayout>...</GridLayout>`?

**Comment by dlucidone** [comment]
Yes, here is  my code 
     
     <Gridlayout id="container1" rows="*" columns = "*,3*,*">
    <Carousel row="0" col="1" height="200" width="200" pageChanged="myChangeEvent" pageTapped="mySelectedEvent" indicatorPadding="10">
    <CarouselItem id="slide1"  verticalAlignment="center" backgroundColor="brown" height="150">
      <Label text="first carousel" color="white" verticalAlignment="center" horizontalAlignment="center"></Label>
    </CarouselItem>
    <CarouselItem id="slide2" verticalAlignment="center" backgroundColor="transparent" height="150">
      <Label text="second crousel" color="white" verticalAlignment="center" horizontalAlignment="center"></Label>
    </CarouselItem>
    <CarouselItem id="slide3" verticalAlignment="center" backgroundColor="transparent" height="150">
      <Label text="third carousel" color="white" verticalAlignment="center" horizontalAlignment="center"></Label>
    </CarouselItem>
    </Carousel>
    </Gridlayout>


the above screenshot is cropped one not the whole emulator.Please help me fix it.Thanks

**Comment by manijak** [comment]
Please try this, the GridLayout around the Caruosel needs only the `rows` property, remove the columns.
Also, make sure you are running the latest version of the plugin, 2.3.1.
```xml
<Gridlayout id="container1" rows="auto">
...
</GridLayout>
```

**Comment by dlucidone** [comment]
@manijak Yess , I have installed the latest version only but now i'm facing problems such as - 
 After installing it as - `tns plugin add nativescript-carousel ` and running the app the app crashes on each page i have `nativescript-floatingActionButtion` don't know why?
I'll test the solution you provided and let you know if it is fixed or not. Thanks for quick replying.

**Comment by manijak** [comment]
No problem. A quick tip regarding the the update of plugins:
- Make sure that package.json has the latest version of the plugin
- Remove the plugin from node_modules folder
- Do a `tns prepare android` then `tns run android`

Sometimes it is also wise to remove the platform and re-add it (if you update many plugins at once).

**Comment by dlucidone** [comment]
@manijak It works like charm. But now i'm getting conflicts on each page of my application where `nativescript-floatingActionButton` is used.

![screen shot 2017-03-01 at 4 27 37 pm](https://cloud.githubusercontent.com/assets/9256365/23457076/35f3f35a-fe9c-11e6-8bd3-939d15d0b8ef.png)


I'm getting error like something.I have to fix it 'coz either way one of the plugin is working not both together. Thanks

**Comment by manijak** [comment]
Glad you got it working. As for the above error, not much I can say. You can try removing platform and re-adding it. Don't think this is directly related to the Carousel plugin. 

Otherwise you could post a issue here: https://github.com/bradmartin/nativescript-floatingactionbutton/issues
