### ISSUE TITLE
Cannot find module androidx && cannot find namespace android

### ISSUE THREAD

**Issue by loonatic** [manijak/nativescript-carousel#130]
![image](https://user-images.githubusercontent.com/17290848/65874081-cad64280-e37c-11e9-987b-a88498a4ec1b.png)

Hello, I've upgraded my NS-Angular app from 5.4 to 6.1 and I'm interested in using your plugin, however the issue on the image is being thrown.

After discussion on NS Slack threads with Eddy Verbruggen, he adviced the use of `global.androidx.appcompat;` instead of `androidx.appcompat;` (on carousel.d.ts file).
Also the change of the `readonly` flag to `declare const ` on Carousel class, line 21.

I will try to make the changes myself and see if it works to then open a PR. However, this is my first time interacting on a plugin so I'm still learning how to do "stuff", so if you are interested I leave all the info here.

Thank you,
Hélder Freitas

**Comment by manijak** [comment]
This error pops up if your build scans the node_modules folder. you can try and add `"skipLibCheck": true` in your `tsconfig.json` and see if it helps.

**Comment by loonatic** [comment]
That flag did the trick, now errors popping up on the console (I'm still unable to open the app as it opens but closes immediately since upgrade to NS 6.1 but that unrelated with the plugin). 

Closing the issue and if issues arise I will let you know. A question though, wouldn't the suggested fixes do the trick? 

Thank you for the answer, Hélder
