### ISSUE TITLE
TypeError: Cannot read property 'ViewPager' of undefined

### ISSUE THREAD

**Issue by Efrenray** [manijak/nativescript-carousel#133]
Migrated my App to NS6 but the version of carousel i'm using is **v3.1.1** which caused this error. should I update it to 6.1.1?

> An uncaught Exception occurred on "main" thread.
> Calling js method onCreateView failed
> TypeError: Cannot read property 'ViewPager' of undefined
> 
> StackTrace:
> 	push.../node_modules/nativescript-carousel/index.js.Carousel.createNativeView(file:///data/data/org.nativescript.ustpsystem/files/app/vendor.js:2112:55)
> 	at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._setupUI(file:///data/data/org.nativescript.ustpsystem/files/app/vendor.js:39495:31)
> 	at (file:///data/data/org.nativescript.ustpsystem/files/app/vendor.js:39537:19)
> 	at push.../node_modules/tns-core-modules/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView(file:///data/data/org.nativescript.ustpsystem/files/app/vendor.js:48322:26)
> 	at push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild(file:///data/data/org.nativescript.ustpsystem/files/app/vendor.js:40811:14)
> 	at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._setupUI(file:///data/data/org.nativescript.ustpsystem/files/app/vendor.js:39536:14)
> 	at (file:///data/data/org.nativescript.ustpsystem/files/app/vendor.js:39537:19)
> 	at push.../node_modules/tns-core-modules/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView(file:///data/data/org.nativescript.ustpsystem/files/app/vendor.js:48322:26)
> 	at push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild(file:///data/data/org.nativescript.ustpsystem/files/app/vendor.js:40811:14)
> 	at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._setupUI(file:///data/data/org.nativescript.ustpsystem/files/app/vendor.js:39536:14)
> 	at (file:///data/data/org.nativescript.ustpsystem/files/app/vendor.js:39537:19)
> 	at push.../node_modules/tns-core-modules/ui/tab-navigation-base/tab-content-item/tab-content-item-common.js.TabContentItemBase.eachChild(file:///data/data/org.nativescript.ustpsystem/files/app/vendor.js:54835:13)
> 	at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._setupUI(file:///data/data/org.nativescript.ustpsystem/files/app/vendor.js:39536:14)
> 	at (file:///data/data/org.nativescript.ustpsystem/files/app/vendor.js:39537:19)
> 	at (file:///data/data/org.nativescript.ustpsystem/files/app/vendor.js:54976:17)
> 	at push.../node_modules/tns-core-modules/ui/tab-navigation-base/tab-navigation-base/tab-navigation-base.js.TabNavigationBase.eachChild(file:///data/data/org.nativescript.ustpsystem/files/app/vendor.js:54975:19)
> 	at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._setupUI(file:///data/data/org.nativescript.ustpsystem/files/app/vendor.js:39536:14)
> 	at (file:///data/data/org.nativescript.ustpsystem/files/app/vendor.js:39537:19)
> 	at push.../node_modules/tns-core-modules/ui/content-view/content-view.js.ContentView.eachChildView(file:///data/data/org.nativescript.ustpsystem/files/app/vendor.js:37242:13)
> 	at push.../node_modules/tns-core-modules/ui/page/page-common.js.PageBase.eachChildView(file:///data/data/org.nativescript.ustpsystem/files/app/vendor.js:49426:40)
> 	at push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild(file:///data/data/org.nativescript.ustpsystem/files/app/vendor.js:40811:14)
> 	at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._setupUI(file:///data/data/org.nativescript.ustpsystem/files/app/vendor.js:39536:14)
> 	at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._addViewCore(file:///data/data/org.nativescript.ustpsystem/files/app/vendor.js:39435:18)
> 	at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._addView(file:///data/data/org.nativescript.ustpsystem/files/app/vendor.js:39424:14)
> 	at push.../node_modules/tns-core-modules/ui/frame/frame.js.FragmentCallbacksImplementation.onCreateView(file:///data/data/org.nativescript.ustpsystem/files/app/vendor.js:45390:19)
> 	at push.../node_modules/tns-core-modules/ui/frame/fragment.js.FragmentClass.onCreateView(file:///data/data/org.nativescript.ustpsystem/files/app/vendor.js:43386:38)
> 	at com.tns.Runtime.callJSMethodNative(Native Method)
> 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1209)
> 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1096)
> 	at com.tns.Runtime.callJSMethod(Runtime.java:1083)
> 	at com.tns.Runtime.callJSMethod(Runtime.java:1063)
> 	at com.tns.Runtime.callJSMethod(Runtime.java:1055)
> 	at com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
> 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
> 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
> 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
> 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
> 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
> 	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
> 	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
> 	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
> 	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
> 	at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
> 	at android.os.Handler.handleCallback(Handler.java:789)
> 	at android.os.Handler.dispatchMessage(Handler.java:98)
> 	at android.os.Looper.loop(Looper.java:164)
> 	at android.app.ActivityThread.main(ActivityThread.java:6541)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
>

**Comment by manijak** [comment]
Yes, you have to.
