### ISSUE TITLE
Carousel images get pushed down if you shake the device

### ISSUE THREAD

**Issue by stpauldev** [manijak/nativescript-carousel#134]
I have successfully implement a carousel on an iOS app, and it is brilliant - works like a charm.

But, I have notice if I shake my phone the images get pushed way down. Has anyone experienced this before?

```
<Carousel width="100%" height="100%" pageChanged="onSwipe($event)" indicatorColor="#fff" indicatorOffset="10,3" finite="true" bounce="false" showIndicator="true" verticalAlignment="top">
                    <CarouselItem id="slide1" verticalAlignment="middle">
                        ...
                    </CarouselItem>
</Carousel>
```

Thanks

**Comment by manijak** [comment]
Wow that is strange... you sure there are no events triggering on share and firing view refresh or something? Never heard of this issue.

**Comment by Nurgunkalol** [comment]
do u have pull to refresh plugin?

**Comment by stpauldev** [comment]
@Nurgunkalol 
I do have the carousel inside a pull to refresh event. Is this the reason why pictures keep moving if you shake your phone?

Here some of the code:

`    <PullToRefresh #pullToRefreshList (refresh)="refreshList($event)"> 
        <ScrollView (scroll)="onScroll($event)">  
            <StackLayout>
                <Label></Label> 
                <Carousel class="toggle" height="100%" width="100%" pageChanged="onSwipe($event)" indicatorColor="#fff" finite="false" bounce="false" showIndicator="true" verticalAlignment="top" android:indicatorAnimation="swap" color="white">
                    <CarouselItem id="slide1" verticalAlignment="middle">
                        <Label text="SLIDE 1" horizontalAlignment="center"></Label>
                        <StackLayout orientation="horizontal" horizontalAlignment="center"> 
                            ...
                        </StackLayout>
                        <Image src="slide1.jpg"></Image>
                    </CarouselItem>
                    <CarouselItem id="slide2" verticalAlignment="middle">
                        <Label text="SLIDE 2" horizontalAlignment="center"></Label>
                        <StackLayout orientation="horizontal" horizontalAlignment="center"> 
                            ...
                        </StackLayout>
                        <Image src="slide2.jpg"></Image>
                    </CarouselItem>
                  
                </Carousel>
              
                <Label></Label>  
                <StackLayout class="print-code" orientation="horizontal" horizontalAlignment="center">
                    ...
                </StackLayout>          
            </StackLayout>             
        </ScrollView>
    </PullToRefresh>`

Thanks
