### ISSUE TITLE
Horizontally center indicator

### ISSUE THREAD

**Issue by GabotronESP** [manijak/nativescript-carousel#136]
I know it's possible to move the indicator position offset by using X and Y coordinates, but how can I place it horizontally centered and 20px from the bottom?

**Comment by manijak** [comment]
Is this iOS or Android? By default the indicator is centered at the bottom. You can use points (x,y) to move the indicator from there: `indicatorOffset="0,20"`. Just make sure you wrap the `Carousel` in a `GridLayout` (android).
