### ISSUE TITLE
Android Height

### ISSUE THREAD

**Issue by alusev** [manijak/nativescript-carousel#138]
Is there a way to set the height of carousel based on its content on Android?
<img width="313" alt="Screen Shot 2020-01-24 at 16 27 29" src="https://user-images.githubusercontent.com/903378/73108636-6e1c0c00-3ec6-11ea-8222-553eff76ee98.png">

It works well on IOS.
<img width="362" alt="Screen Shot 2020-01-24 at 16 28 33" src="https://user-images.githubusercontent.com/903378/73108684-93107f00-3ec6-11ea-82bd-a975b305d86d.png">

Code:
```
<StackLayout col="0" row="1" colSpan="3" style="padding: 10 0">

        <Carousel [items]="rewards" width="100%" showIndicator="false" (pageChanged)="onIndexChanged($event)">
            <CarouselItem *ngFor="let items of rewards" verticalAlignment="middle">
                <Label text="text" backgroundColor="green"></Label>
            </CarouselItem>
        </Carousel>

        <StackLayout style="padding-top: 8">
            <PageIndicator [dotSize]="10" [currentPage]="page" [numPages]="rewards.length"></PageIndicator>
        </StackLayout>

</StackLayout>
```

**Comment by manijak** [comment]
No sorry this is not possbile. The height is decided but Carousel height or parent container.
