### ISSUE TITLE
Indicator offset

### ISSUE THREAD

**Issue by mrcretu** [manijak/nativescript-carousel#139]
Hello, thanks for this awesome plugin. I want to ask about the indicator offset, more exactly what means the value? I don't think that are pixels. I want to align the indicator at the left of the screen with margin 20. I don't find a formula or something to calculate the xOffset depending on multiple devices and widths.
 Can you help me to accomplish that?
Thanks in advance!

**Comment by markosole** [comment]
@mrcretu can you be more precise and can you provide example as image what you trying to do and I'll try to help.

**Comment by mrcretu** [comment]
@markosole Hey, sure I can provide an example.
[https://www.dropbox.com/s/9rkd8hifdmryccl/Screenshot%202020-03-06%20at%2010.28.33.png?dl=0](url)
I want to align the indicator on the left of the screen as shown on the emulator 2(the one placed in middle), also I want a margin-left of 20 to start where text sections starts. By simply hardcoding indicator's offsets I can't accomplish that, I also tried to figure it out a formula to calculate the offset for each devices by taking widthDIPs but no success.

**Comment by manijak** [comment]
Think your link is broken. 
Is this on iOS or Android? I honestly have not had any issues across devices by using the indicator offsets. By default it is centered at the bottom. Then by using the `indicatorOffset` (x,y points) you can align it to your liking. So in order to move it to the left side, it needs to have a negative value on x.

**Comment by mrcretu** [comment]
https://www.dropbox.com/s/9rkd8hifdmryccl/Screenshot%202020-03-06%20at%2010.28.33.png?dl=0
Sorry for the link, @manijak for the example I've set, as you say, the indicator offset like so: 
`indicatorOffset="-160, -20"` but it's aligned as I want only for one device, the one in the middle(iPhone 11 PRO Max). On left side I have a tablet(iOS) and at the right side I have an Android emulator.
Maybe it's something I don't know or I do wrong. Thanks for answers.

**Comment by manijak** [comment]
No you are doing everything correct. I should have known, it just takes the offset from center, so it will be like this across devices & resolutions. I think the only solution right now is like you said a formula to calculate the width and divide it by 2 and use that as offset for x (+- some margin).

**Comment by mrcretu** [comment]
@manijak Thanks!
I was able to accomplish my needs by using the following computation:
`if (isAndroid) {
            this.offsetX =  ((screen.mainScreen.widthDIPs / 2) * -1 + 40) * 2;
        } 
        else {
            this.offsetX = (screen.mainScreen.widthDIPs / 2) * -1 + 40;
        }
`

Where 40 is the margins: left(20) & right(20). For android I found that DIP is (2 x DIP) for iOS because of iOS's retina screen.
Hope this will help another person in the future.
And also thanks for the support.

**Comment by manijak** [comment]
Great, good job 👍. Yes, I have a similar formula for some image rendering, and yes, iOS & Android have a slight differences in DIPs.
