### ISSUE TITLE
Android Image stretch doesn't work

### ISSUE THREAD

**Issue by RGBvision** [manijak/nativescript-carousel#144]
On Android (TNS 6.3) I set the stretch parameter to aspectFill, but it has no effect.
`<Image src="{{ image }}" stretch="aspectFill"/>`

I didn't test on iOS.

**Comment by manijak** [comment]
You posted only the code related to the `Image`, how does the rest look like (`Carousel` ect)?

**Comment by RGBvision** [comment]
```
<GridLayout height="200" class="order-photo">
  <ns:Carousel id="myCarousel" color="white" height="100%" width="100%" finite="true" bounce="false" android:indicatorAnimation="fill" items="{{ images }}" indicatorColor="#fff" indicatorOffset="0, -10" showIndicator="true">
    <ns:Carousel.itemTemplate>
      <ns:CarouselItem padding="0">
        <GridLayout>
          <Image src="{{ image }}" stretch="aspectFill"/>
          <Label text="{{ title }}" horizontalAlignment="right" verticalAlignment="bottom" backgroundColor="#7f000000" height="30"/>
        </GridLayout>
      </ns:CarouselItem>
    </ns:Carousel.itemTemplate>
  </ns:Carousel>
</GridLayout>
```

**Comment by manijak** [comment]
Did you try adding `width="100%" height="100%"` to the `Image`?

**Comment by RGBvision** [comment]
Yes. No effect =(

**Comment by RGBvision** [comment]
Problem appears if Carousel is inside ListView. I think that the problem is not in the carousel but with Image element. Inside ListView `stretch="aspectFill"` doesn't affects Image.

**Comment by manijak** [comment]
Think I've mentioned this in another issue, `Carousel` has not been tested with `ListView`, nor was it intended to be used inside one.
