### ISSUE TITLE
Indicator not showing

### ISSUE THREAD

**Issue by UNIcodeX** [manijak/nativescript-carousel#145]
Not sure what I'm doing wrong. My images load up using template mode from the supplied data, I can scroll them, the labels change, etc...

The indicator dots are not showing even with all of the indicatorXXX properties having been set.

In the demo, the indicators show. I copied and pasted code from the demo into my app, so I'm not sure what's wrong.

Happens on:
- Android X
- Android 7.0
- Probably others

NativeScript version: 6.4.1 and latest version of nativescript-carousel as installed with `tns plugin add nativescript-carousel`.

page.xml
```xml
<ns:Carousel 
    id="carousel" column="0" row="1" colSpan="3" rowSpan="5" 
    visibility="{{ carouselVisibility }}" debug="true" color="white" 
    pageChanged="carouselChangeEvent" android:indicatorAnimation="slide" 
    items="{{ results }}" indicatorColor="red" indicatorColorUnselected="black"
    showIndicator="true" style="z-index:1;" height="100%" indicatorAlignment="bottom" 
    indicatorRadius="50" indicatorOffset="100,100" finite="false" bounce="true">
        <ns:Carousel.itemTemplate>
            <ns:CarouselItem backgroundColor="black" verticalAlignment="middle" tap="carouselTapEvent">
                <GridLayout>
                    <Image src="{{ datasetItem1 }}" stretch="aspectFill" />
                    <Label text="{{ datasetItem2 }}" horizontalAlignment="center" verticalAlignment="top" class="carousel-label"/>
                    <Label text="{{ datasetItem3 }}" horizontalAlignment="center" verticalAlignment="bottom" class="carousel-label"/>
                </GridLayout>
            </ns:CarouselItem>
        </ns:Carousel.itemTemplate>
    </ns:Carousel>
```

**Comment by manijak** [comment]
Hi there. Wrap the `Carousel`  in a `GridLayout` and see if it helps :)

**Comment by UNIcodeX** [comment]
Well... It was already in a GridLayout, but it wasn't the only child of that GridLayout. So... I put a GridLayout in my GridLayout (LOL) and now it's giving me the indicators!

Thanks! Cheers!!
