### ISSUE TITLE
WARNING: parse() is deprecated. Use Builder.parse() instead

### ISSUE THREAD

**Issue by UNIcodeX** [manijak/nativescript-carousel#148]
Getting warning in console when using nativescript-carousel. 

https://stackoverflow.com/questions/58566713/nativescript-depreciationwarning-parse-is-deprecated-use-builder-parse-in

**Comment by acutedeveloper** [comment]
Looks like a src/carousel.ios.ts needs to import Builder instead. Will try a get a PR in.

**Comment by UNIcodeX** [comment]
I'm getting this on Android also, though.

**Comment by UNIcodeX** [comment]
Hello. Checking in on whether anything has been done on this.

**Comment by UNIcodeX** [comment]
nice! When do you think the next release will be?

**Comment by manijak** [comment]
Released
