### ISSUE TITLE
Nativescript 7.0 compatibility

### ISSUE THREAD

**Issue by Upd4ting** [manijak/nativescript-carousel#166]
Hello since nativescript 7.0 i'm having theses issues

```
ERROR in ../node_modules/nativescript-carousel/carousel.common.js
Module not found: Error: Can't resolve 'tns-core-modules/color/color' in 'C:\Users\vulks\Downloads\meteor-nativescript-template\node_modules\nativescript-carousel'
 @ ../node_modules/nativescript-carousel/carousel.common.js 7:14-53
 @ ../node_modules/nativescript-carousel/carousel.js
 @ ./main.ts
```

```
ERROR in ../node_modules/nativescript-carousel/carousel.common.js
Module not found: Error: Can't resolve 'tns-core-modules/data/observable-array/observable-array' in 'C:\Users\vulks\Downloads\meteor-nativescript-template\node_modules\nativescript-carousel'       
 @ ../node_modules/nativescript-carousel/carousel.common.js 9:25-91
 @ ../node_modules/nativescript-carousel/carousel.js
 @ ./main.ts
```

```
ERROR in ../node_modules/nativescript-carousel/carousel.common.js
Module not found: Error: Can't resolve 'tns-core-modules/ui/core/weak-event-listener/weak-event-listener' in 'C:\Users\vulks\Downloads\meteor-nativescript-template\node_modules\nativescript-carousel'
 @ ../node_modules/nativescript-carousel/carousel.common.js 13:28-103
 @ ../node_modules/nativescript-carousel/carousel.js
 @ ./main.ts
```

Any idea?

**Comment by manijak** [comment]
NS7 compatibility has been merged to master but not released yet.

**Comment by Upd4ting** [comment]
Do you plan to release it fast or do you advice me to rollback to 6.5?

**Comment by Upd4ting** [comment]
As I needed that asap I used [patch-package](https://www.npmjs.com/package/patch-package) to create a patch file for that.

For thoses who need that, use that patch file: 

[nativescript-carousel+6.1.1.zip](https://github.com/manijak/nativescript-carousel/files/5213565/nativescript-carousel%2B6.1.1.zip)

@manijak  While creating this patch file, I saw that you are missing something for ns 7.0 compatibility. You missed the step described [here](https://nativescript.org/blog/nativescript-7-for-plugin-authors/) to ensure nativeclass is processed. You correctly added 

```
"compilerOptions": {
  "plugins": [{
    "transform": "@nativescript/webpack/transformers/ns-transform-native-classes",
    "type": "raw"
  }]
}
```

but you didn't install `ts-patch` and didn't run `ts-patch install` as described by nativescript blog.

If you could please fix that asap and release it it would be very appreciated. In the meanwhile, i'll use patch-package.

**Comment by manijak** [comment]
I have only merged PR from other community members to master. Nothing is tested or guaranteed to be working. 

There won't be any "asap" releases from me on this. I'm currently preoccupied with other work and my MacBook for this work is being serviced. Until then feel free to fix the issues and send in a PR.

**Comment by bradmartin** [comment]
@manijak - I'd like to help get this out. So I'll review the recent PR about ts-patch and then I can get everything in sync for a major bump 💯

**Comment by manijak** [comment]
Thanks for the PRs guys. New version published. 👍
