### ISSUE TITLE
Nativeclass not transpiled correctly in the last release 7.0.0

### ISSUE THREAD

**Issue by Upd4ting** [manijak/nativescript-carousel#169]
Hey there it seems you haven't build the plugin correctly in the last release because `nativeclass` is not transpiled correctly.

Could you rebuild it and republish that?

**Comment by manijak** [comment]
Published 7.0.1 with a potential fix. Let me know if this helps :)

**Comment by Upd4ting** [comment]
It seems to be good this time, thank you!
