### ISSUE TITLE
Swipe do not work on IOS.

### ISSUE THREAD

**Issue by raul26** [manijak/nativescript-carousel#17]
Hello I'm using your awesome plugin and I'm facing an issue with IOS.
I'm working with [Telerik UI chart](http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/overview) and when the swipe happens over the graph the event is not triggered.
I posted a question in [Telerik Forum](http://www.telerik.com/forums/swipe-event).
Is there any workaround to make it work as expected?

Any help is welcomed

**Comment by manijak** [comment]
Hi there @raul26, I've added a reply to the forum topic. :)

**Comment by raul26** [comment]
Hi @manijak thank you so much :)

**Comment by manijak** [comment]
Closing this as there is no new information...
