### ISSUE TITLE
Not working with Vanilla JS Projekt

### ISSUE THREAD

**Issue by svrecer** [manijak/nativescript-carousel#177]
Hi

I have a Vanilla JS nativescript Project
I'm using the latest version of nativescript-carousel
I followed the instructions but am unable to make it work

package.json:
"""
...
 "tns-android": {
      "version": "6.5.0"
    },
    "tns-ios": {
      "version": "6.5.0"
    }
...
    "nativescript-carousel": "^7.0.1",
...
  "devDependencies": {
    "nativescript-dev-webpack": "~1.5.0"
  },
...
"""
main-page.xml:
"""
<Page xmlns="http://schemas.nativescript.org/tns.xsd"
      xmlns:FAB="@nstudio/nativescript-floatingactionbutton"
      xmlns:au="nativescript-ui-autocomplete"
      xmlns:Gif="nativescript-gif"
      **xmlns:ns="nativescript-carousel"**
      navigatingTo="onNavigatingTo"
...
    <GridLayout class="{{ displayHelpPage ? 'yellow-back' : ''}}" rows="*,40">
        **<ns:Carousel>
                <ns:CarouselItem id="slide1" verticalAlignment="middle">
                    <Label text="Each slide is defined in the XML" textWrap="true" margin="30" />
                </ns:CarouselItem>

                <ns:CarouselItem id="slide2" verticalAlignment="middle">
                    <Label text="'finite' is set to False. Carousel will not stop at the last slide" textWrap="true" margin="30"/>
                </ns:CarouselItem>
        </ns:Carousel>**
...
"""

When I try to run the app I get an error saying

An uncaught Exception occured on "main" thread.
Unable to start activity 
ComponentInfo{com.xsot.insat/com.tns.NativeScriptActivity}:
com.tns.NativeScriptException: Calling js method onCreate failed
Error: Building UI from XML. @app-root.xml:1:1
 > Building UI from XML. @main-page.xml:32:9
  > Module 'nativescript-carousel' not found for element 'nativescript-carousel:Carousel'.
   > _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor

What am I doing wrong?
Please Help!

**Comment by manijak** [comment]
You are using version 7.0.x of the plugin, that is ment for projects running NS7. 

If you want to use the plugin on ns 6.x then you need to install version 6.1.1 of the plugin.

**Comment by svrecer** [comment]
Thank you very much!
