### ISSUE TITLE
plugin breaks with new nativescript version

### ISSUE THREAD

**Issue by developper89** [manijak/nativescript-carousel#20]
When i am building it crashes with message :
> Could not find com.android.support:support-core-ui:25.3.0
> Could not find com.android.support:support-annotations:25.3.0.
> Could not find com.android.support:support-compat:25.3.0

**Comment by manijak** [comment]
The message states that your are missing the latest Android SDK version... The Android page-indicator requires the latest version. So to solve it, you need to install SDK v25.x
