### ISSUE TITLE
On Android carousel not updating when items bound to ObservableArray

### ISSUE THREAD

**Issue by terreb** [manijak/nativescript-carousel#23]
When items are bound to ObservableArray and it's changed the carousel is not updating. However on iOS this works fine.

To test please copy-paste the next 2 snippets to respective files in demo.

main-page.xml:
```xml
<Page xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:ns="nativescript-carousel" loaded="pageLoaded" navigatingTo="onNavigatingTo">
      <!-- UI Decalration -->
      <GridLayout height="250">
        <ns:Carousel id="myCarousel"
                     height="250"
                     color="white"
                     pageChanged="myChangeEvent"
                     pageTapped="mySelectedEvent"
                     loaded="onSlideContainerLoaded"
                     items="{{ myDataArray }}">
          <ns:Carousel.itemTemplate>
            <ns:CarouselItem  verticalAlignment="center" backgroundColor="{{ color }}" height="250">
              <GridLayout rows="*" columns="*,*">
                <Image src="{{ image }}" height="100" col="1" tap="onButtonTap"/>
                <Button col="0" text="TAP ME" id="buttonOne" tap="onButtonTap" />

              </GridLayout>
            </ns:CarouselItem>
          </ns:Carousel.itemTemplate>
        </ns:Carousel>
      </GridLayout>
    </Page>
```

main-page.js:
```javascript
       var obeservableArray = require('data/observable-array');
        var pageData = new observableModule.Observable();
        var myDataArray = [
            {title:"Slide 1", color: "#b3cde0", image:"https://raw.githubusercontent.com/manijak/nativescript-photoviewer/master/demo/res/01.jpg"},
            {title:"Slide 2", color: "#6497b1", image:"https://raw.githubusercontent.com/manijak/nativescript-photoviewer/master/demo/res/02.jpg"},
            {title:"Slide 3", color: "#005b96", image:"https://raw.githubusercontent.com/manijak/nativescript-photoviewer/master/demo/res/03.jpg"},
            {title:"Slide 4", color: "#03396c", image:"https://raw.githubusercontent.com/manijak/nativescript-photoviewer/master/demo/res/04.jpg"}
        ];
        var items = new obeservableArray.ObservableArray()
        pageData.set("myDataArray", items);
        
        setTimeout(function() {
            items.push(myDataArray)
        }, 5000)
        
        exports.pageLoaded = function(args) {
            var page = args.object;
            page.bindingContext = pageData;
        }
```

My config:
nativescript-carousel 2.4.2
tns 2.5.4
tns-core-modules 2.5.2
tns-android 2.5.0
tns-ios 2.5.0
Genymotion 2.8.1 Samsung Galaxy S7 - 6.0.0

**Comment by terreb** [comment]
@manijak is there a workaround for this? Can I somehow make the carousel refresh explicitly?

**Comment by jbfulgencio** [comment]
+1

**Comment by manijak** [comment]
Sorry about the late reply. 
Your code works just fine, just call the `pageData.set("myDataArray", items);` explicitly, right after the array is updated. 

In your case, something like this:
```js
setTimeout(function() {
      items.push(myDataArray)
      pageData.set("myDataArray", items);
}, 5000)
```

**Comment by BramRausch** [comment]
Hey, I ran into the same problem and adding ```pageData.set("myDataArray", items); ``` didn't work out for me but when I did this it worked for me.
```
pageData.set("myDataArray", items); 
page.getViewById("<carousel-id>").refresh();
```

**Comment by manijak** [comment]
Yeah there is a `refresh()` function in the plugin, but the idea was that you should not have to call it manually. Since it is already called by the `_onItemsPropertyChanged`. In other words, when the items-array bound to the Carousel is changed. 

But I think it's all about proper timing, just make sure that you do UI-related operations when the view is done loading. Even data-binding towards UI elements.

**Comment by terreb** [comment]
@manijak Ok, but why don't I need to add pageData.set("myDataArray", items) inside setTimeout on iOS and do need on Android? Why iOS handles this on its own, but not Android? I'm totally ok with your suggestion, but it's just interesting for me to understand the difference. Thanks.

**Comment by manijak** [comment]
The logic for both is basically the same, they both clean their Carousel items and re-create everything. 

As to why it works on iOS and not on Android, that is a question I've asked my self many times when doing cross-platform development 😄 . Each platform is different in its own way, and you cannot expect everything to be identical. In this case it could be how fast each platform is loading the UI elements prior to binding. 

Make sure you test your iOS solution on a real device, you might be surprised...

**Comment by terreb** [comment]
Haha, true indeed, with regards to "...why it works on iOS and not on Android, that is a question I've asked my self many times when doing cross-platform development".

Also with regards to surprises, iOS rarely gives me surprises when I switch from simulator to a real device unlike Android where I often get different "surprises" regardless the chosen tool Nativescript, Cordova, etc..:)

Anyway, thanks for your help and the best carousel plugin for Nativescript so far!

**Comment by manijak** [comment]
This should be fixed in the latest version.
