### ISSUE TITLE
Slide programmaticlaly

### ISSUE THREAD

**Issue by developper89** [manijak/nativescript-carousel#29]
Hi,

Is it possible to enable/disable the slide gesture ?
What if we have some steps to achieve before switching to the next slide

**Comment by manijak** [comment]
In the next version, iOS will get `scrollEnabled` property. But nothing on Android for the time being.

**Comment by manijak** [comment]
Btw, just published the mentioned version to npm.

**Comment by manijak** [comment]
https://github.com/manijak/nativescript-carousel/issues/34
Duplicate, closing this.
