### ISSUE TITLE
Ng2 implementation for ios?

### ISSUE THREAD

**Issue by dlucidone** [manijak/nativescript-carousel#32]
I'm getting error like this -

`CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:344:22: Error: Uncaught (in promise): Error: Error in /Users/Dlucidone/Library/Developer/CoreSimulator/Devices/D9C7FD67-A0D7-42F7-98B4-4C8D78CFD0B7/data/Containers/Bundle/Application/0823DC50-9FA1-498A-90F1-3108FE70A804/PulseIos.app/app/login/login.component.html:17:0 caused by: undefined is not a constructor (evaluating 'new viewClass()')`

Any example on readme or demo will be really helpful.

**Comment by manijak** [comment]
I'm sorry, but I cannot see from the above error how this has anything to do with this plugin?

**Comment by dlucidone** [comment]
Can You add sample app with ng2 ? It will help. Thanks

**Comment by hettiger** [comment]
@dlucidone Here’s a sample app that I‘ve made: https://github.com/hettiger/nativescript-carousel-ng-example

**Comment by manijak** [comment]
There are several examples available for ng2, including a demo app. Closing
