### ISSUE TITLE
iOS: 2 Slides causes issues

### ISSUE THREAD

**Issue by sitefinitysteve** [manijak/nativescript-carousel#39]
So I only see this as an issue with 2 slides in the carousel... you can see just SLIGHTLY moving the scroll it pops the image from slide 2 over to slide 1 😕   It's not just the image though it's like every bound element just gets replaced.

If I add a 3rd slide, it's all fine again.

Sample:
https://www.dropbox.com/s/vhiknzno1p9hnsm/carousel-test.zip?dl=0

**Comment by sitefinitysteve** [comment]
*EDIT* Sorry the gifs were just terrible, here's a video

https://www.screencast.com/t/LmiGowjd

**Comment by sitefinitysteve** [comment]
Can even be replicated with a simple declarative example
```
        <ns:Carousel row="0" height="100%" ios:finite="true" ios:bounce="false" android:indicatorAlignment="bottom" android:indicatorRadius="4">
            
               <ns:CarouselItem id="slide1"  verticalAlignment="center" backgroundColor="#b3cde0">
                    <Label text="Slide 1" verticalAlignment="center" horizontalAlignment="center"/>
                </ns:CarouselItem>
                <ns:CarouselItem id="slide2" verticalAlignment="center" backgroundColor="#6497b1">
                    <Label text="Slide 2" verticalAlignment="center" horizontalAlignment="center"/>
                </ns:CarouselItem>

        </ns:Carousel>
```

**Comment by sitefinitysteve** [comment]
Verified it's fine on android

**Comment by sitefinitysteve** [comment]
Burned all afternoon on this... looks like it's this chunk of code causing it

https://github.com/sitefinitysteve/DKCarouselView/blob/master/DKCarouselView/DKCarouselView.m#L403-L417

I'm not sure WHAT it's for, but killing it makes it behave as expected

https://www.screencast.com/t/BJm3byqc

**Comment by manijak** [comment]
Thanks @sitefinitysteve  did you manage to add a PR to this? Agree that this function is a bit weird...

**Comment by sitefinitysteve** [comment]
I have not, do you need me to?  Figured you could have a look at it and kill if it works on your end.

HERE I have it pointing at my repo and everything works great, I don't know why it's there...

**Comment by manijak** [comment]
Roger that, I'll take a look at it.

**Comment by manijak** [comment]
Pod updated and published with the new version of the Carousel 3.1.1. Closing this.

**Comment by manijak** [comment]
Related to issue #59

**Comment by sitefinitysteve** [comment]
My fix works... ;)

**Comment by manijak** [comment]
Your fix is already applied, but there seems to be issue if you are using `finite` or not
