### ISSUE TITLE
question: how to change slides programatically

### ISSUE THREAD

**Issue by terreb** [manijak/nativescript-carousel#4]
Hi! First off thank you for the plugin! A have a few questions: how can I change slides programatically? And also, are there plans to make inner interactive views (i.e. buttons) to react on taps? Is there a workaround to make them so now? Thank you in advance!

**Comment by manijak** [comment]
You can switch pages by setting the `selectedPage` property of the Carousel. 

I have an idea on how to make the Carousel interactive on iOS, so yeah, I am working on it, but no ETA at the moment. :) There is no simple workaround since I have to modify the original library.

**Comment by terreb** [comment]
Ok, thanks this works!

**Comment by terreb** [comment]
Hey @manijak I don't know what you meant under interactive components not working, but tap event added to a button or even image inside a slide work perfectly fine. Tried with simulator iOS 9.3 and 10.1. Both work:)

**Comment by manijak** [comment]
Hmmmm... strange, did not work for me initially. Will do some more tests. Thanks for the feedback!

**Comment by EddyVerbruggen** [comment]
Yep, works great x-platform. Angular example for anyone needing this (in my case I wanted a button to also trigger the slide effect):

view:
```html
<Carousel #carousel ..>
  <Button text="Next slide" (tap)="moveToSlideIndex(1)"></Button>
  ..
</Carousel>
```


.component.ts:
```js
const Carousel = require("nativescript-carousel").Carousel;
const CarouselItem = require("nativescript-carousel").CarouselItem;

// register the Carousel plugin so its namespace can be used in the view
registerElement("Carousel", () => Carousel);
registerElement("CarouselItem", () => CarouselItem);

export class SlidesComponent {
  @ViewChild("carousel") carousel: ElementRef;

  moveToSlideIndex(slide: number): void {
    let slides = this.carousel.nativeElement;
    slides.selectedPage = slide;
  }
  ..
}
```

**Comment by FlawaCLV** [comment]
@EddyVerbruggen works great but doesn't prevent the user from sliding himself. How do I keep track of the change ?

The doc says selectedPage is gets/sets, but `(selectedPage)=""` isn't working. Is there a change event something like that ?
