### ISSUE TITLE
Module Not Found

### ISSUE THREAD

**Issue by justmykk** [manijak/nativescript-carousel#46]
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.groceries/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error: Building UI from XML. @file:///app/views/login/login-page.xml:16:9
 > Module '/data/data/org.nativescript.groceries/files/app/nativescript-carousel' not found for element 'nativescript-carousel:Carousel'.
   > com.tns.NativeScriptException: Failed to find module: "/data/data/org.nativescript.groceries/files/app/nativescript-carousel", relative to: app//
      com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1043)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:925)
    com.tns.Runtime.callJSMethod(Runtime.java:912)
    com.tns.Runtime.callJSMethod(Runtime.java:896)
    com.tns.Runtime.callJSMethod(Runtime.java:888)
    com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
    android.app.Activity.performCreate(Activity.java:6237)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    android.app.ActivityThread.-wrap11(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
File: "file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/ui/builder/builder.js, line: 195, column: 20

StackTrace: 
	Frame: function:'ScopeError', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/utils/debug.js', line: 17, column: 24
	Frame: function:'SourceError', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/utils/debug.js', line: 28, column: 23
	Frame: function:'', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 214, column: 17
	Frame: function:'', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 195, column: 33
	Frame: function:'', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/xml/xml.js', line: 148, column: 13
	Frame: function:'EasySAXParser.parse', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/js-libs/easysax/easysax.js', line: 751, column: 23
	Frame: function:'XmlParser.parse', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/xml/xml.js', line: 195, column: 22
	Frame: function:'XmlStringParser.parse', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 201, column: 27
	Frame: function:'parseInternal', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 46, column: 11
	Frame: function:'loadPage', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 130, column: 27
	Frame: function:'pageFromBuilder', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 128, column: 26
	Frame: function:'resolvePageFromEntry', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 112, column: 20
	Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 180, column: 20
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 706, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25

	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error: Building UI from XML. @file:///app/views/login/login-page.xml:16:9
 > Module '/data/data/org.nativescript.groceries/files/app/nativescript-carousel' not found for element 'nativescript-carousel:Carousel'.
   > com.tns.NativeScriptException: Failed to find module: "/data/data/org.nativescript.groceries/files/app/nativescript-carousel", relative to: app//
      com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1043)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:925)
    com.tns.Runtime.callJSMethod(Runtime.java:912)
    com.tns.Runtime.callJSMethod(Runtime.java:896)
    com.tns.Runtime.callJSMethod(Runtime.java:888)
    com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
    android.app.Activity.performCreate(Activity.java:6237)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    android.app.ActivityThread.-wrap11(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
File: "file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/ui/builder/builder.js, line: 195, column: 20

StackTrace: 
	Frame: function:'ScopeError', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/utils/debug.js', line: 17, column: 24
	Frame: function:'SourceError', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/utils/debug.js', line: 28, column: 23
	Frame: function:'', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 214, column: 17
	Frame: function:'', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 195, column: 33
	Frame: function:'', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/xml/xml.js', line: 148, column: 13
	Frame: function:'EasySAXParser.parse', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/js-libs/easysax/easysax.js', line: 751, column: 23
	Frame: function:'XmlParser.parse', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/xml/xml.js', line: 195, column: 22
	Frame: function:'XmlStringParser.parse', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 201, column: 27
	Frame: function:'parseInternal', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 46, column: 11
	Frame: function:'loadPage', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 130, column: 27
	Frame: function:'pageFromBuilder', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 128, column: 26
	Frame: function:'resolvePageFromEntry', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 112, column: 20
	Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 180, column: 20
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 706, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25

	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1043)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:925)
	at com.tns.Runtime.callJSMethod(Runtime.java:912)
	at com.tns.Runtime.callJSMethod(Runtime.java:896)
	at com.tns.Runtime.callJSMethod(Runtime.java:888)
	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
	at android.app.Activity.performCreate(Activity.java:6237)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
	... 9 more

**Comment by manijak** [comment]
Make sure the plugin is installed properly (that it exists in the node_modules folder after build).
Version 3.x of the plugin requires TNS 3.x

**Comment by justmykk** [comment]
I uninstalled the plugin and reinstalled, still getting the same error. I can see it in my node_modules folder.
Using TNS 3.1.3

**Comment by manijak** [comment]
Just tested on tns 3.1.3 and it works fine both on iOS and Android. Please test the demo app included here on git.

**Comment by justmykk** [comment]
Thanks for the response @manijak. I've been able to get it working using "tns plugin add nativescript-carousel" instead of "npm i nativescript-carousel" which I was using earlier.
