### ISSUE TITLE
Error: Cannot read property 'notifyDataSetChanged' of null,undefined 

### ISSUE THREAD

**Issue by OPADA-Eng** [manijak/nativescript-carousel#49]
I'm getting this error message when I put dynamic slides carousel in a page and create the bindingContext in "navigatingTo" event,
this issues disappeared when I used "loaded" event and the carousel worked fine but that is not preferable for me because other components is not working after that.
How can I resolve this problem ?
Thanks.

**Comment by manijak** [comment]
You are getting the error because the UI has not been loaded yet, that is why it is preferable to set the binding in the loaded event.  `notifyDataSetChanged` is being called on a UI component in the plugin, and it is currently `null`...

Sorry, but I don't have any other solution to this.

**Comment by OPADA-Eng** [comment]
Can you please just set this check:
`if(adapter) {
            adapter.notifyDataSetChanged();
            this._pageIndicatorView.setCount(this.items.length);
            this.nativeView.setCurrentItem(this.selectedPage);
            this._pageIndicatorView.setSelection(this.selectedPage);
        }`
or accept my PR.
Thanks

**Comment by manijak** [comment]
Merged, thanks!

**Comment by OPADA-Eng** [comment]
Welcome, 
Can you please update npm repo to use the changes in my project ?

**Comment by OPADA-Eng** [comment]
Thanks
