### ISSUE TITLE
Can't make the carousel work 

### ISSUE THREAD

**Issue by moda20** [manijak/nativescript-carousel#50]
hello ! 
i am using this component in my nativescript app and i didn't find a way to make it work. I installed the npm package and used the manual carousel example from the docs but it didn't work. all the labels appear on top of each other no sliding is working.
this is the code i am using it just is the exact same code from the docs.
`<page xmlns:ns="nativescript-carousel">

        <ns:Carousel height="250" pageChanged="myChangeEvent">
            <ns:CarouselItem id="slide1"  verticalAlignment="center" backgroundColor="#b3cde0">
                <Label text="Slide 1" verticalAlignment="center" horizontalAlignment="center"></Label>
            </ns:CarouselItem>
            <ns:CarouselItem id="slide2" verticalAlignment="center" backgroundColor="#6497b1">
                <Label text="Slide 2" verticalAlignment="center" horizontalAlignment="center"></Label>
            </ns:CarouselItem>
            <ns:CarouselItem id="slide3" verticalAlignment="center" backgroundColor="#005b96">
                <Label text="Slide 3" verticalAlignment="center" horizontalAlignment="center"></Label>
            </ns:CarouselItem>
        </ns:Carousel>
   
</page>`
any help ?

**Comment by moda20** [comment]
It doesn't build successfully 
Error : 
`Execution failed for task ':mergeF0F1DebugResources'.
> Error: Failed to crunch file C:\Users\THERONIN\Downloads\nativescript-carousel-master\nativescript-carousel-master\demo\platforms\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\26.0.0-alpha1\res\drawable-hdpi-v4\abc_ic_menu_share_mtrl_alpha.png into C:\Users\THERONIN\Downloads\nativescript-carousel-master\nativescript-carousel-master\demo\platforms\android\build\intermediates\res\merged\F0F1\debug\drawable-hdpi-v4\abc_ic_menu_share_mtrl_alpha.png`

**Comment by manijak** [comment]
Don't see what those errors have to do with the plugin...

**Comment by cydrake** [comment]
registerElement('Carousel', () => require('nativescript-carousel').Carousel);
registerElement(
    'CarouselItem',
    () => require('nativescript-carousel').CarouselItem
);
