### ISSUE TITLE
How to use the plugin with Angular?

### ISSUE THREAD

**Issue by mutazmq** [manijak/nativescript-carousel#53]
I'm building an app with Nativescript + Angular, but I don't know how to use your plugin in this settings. It seems that your demo is only for Nativescript apps. Can I use it for Nativescript + Angular? And if yes, can you please tell me how? 

Thank you

**Comment by asaph26** [comment]
@mutazmq There is an open issue regarding this. You can follow the discussion in that thread. The current working suggestion is https://github.com/manijak/nativescript-carousel/issues/5#issuecomment-339986674
