### ISSUE TITLE
Crash on navigate out\back under android

### ISSUE THREAD

**Issue by sitefinitysteve** [manijak/nativescript-carousel#55]
I have a button which opens a chrome and\or google maps.  So I nav over there, but navigating back and trying to change "pages" throws this:

![image](https://user-images.githubusercontent.com/1542376/32084795-4e8a0b98-ba99-11e7-99d4-09f39f0d8783.png)

**Comment by manijak** [comment]
Hmmm... this one is new to me. You are not by any chance running tns 3.3?

**Comment by sitefinitysteve** [comment]
I am...

**Comment by manijak** [comment]
I have not tested the plugin with 3.3... so I have no idea what might be the issue here.

**Comment by sitefinitysteve** [comment]
I can back out to 3.2 and see if it still happens

**Comment by manijak** [comment]
I just tested the plugin on 3.3, android & ios. Seems to work just fine from my end. With and without navigation and back.

**Comment by sitefinitysteve** [comment]
Were opening an advanced webview then moving around again... I have the app
in review by the team now, thx for checking

**Comment by manijak** [comment]
@sitefinitysteve did manage to solve this?

**Comment by sitefinitysteve** [comment]
"Solve" I don't think so... I mean it's caused by the markingmode apparently... we can close here yeah it's their issue
