### ISSUE TITLE
Error when building for Android

### ISSUE THREAD

**Issue by erjdriver** [manijak/nativescript-carousel#58]
I' m running NS 3.3 and get the following error when compiling for Android - same error on demo.

Works fine for iOS - even though there's coupla API warnings.

Project was building before I added the plug-in.

Also did a "tns platform remove android"

`Searching for devices...
Executing before-prepare hook from /Users/asrock/Documents/ns-layovers/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 2.4.2
Preparing project...
Successfully prepared plugin nativescript-carousel for android.
Successfully prepared plugin nativescript-theme-core for android.
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Project successfully prepared (Android)
Building project...
Gradle build...
         + applying user-defined configuration from /Users/asrock/Documents/ns-layovers/app/App_Resources/Android/app.gradle
         + add include.gradle from /Users/asrock/Documents/ns-layovers/node_modules/nativescript-carousel/platforms/android/include.gradle
         + creating include.gradle for plugin /Users/asrock/Documents/ns-layovers/node_modules/tns-core-modules-widgets
         + applying plugin configuration from /Users/asrock/Documents/ns-layovers/platforms/android/build/configurations/nativescript-carousel/include.gradle
         + applying plugin configuration from /Users/asrock/Documents/ns-layovers/platforms/android/build/configurations/tns-core-modules-widgets/include.gradle
         + adding nativescript runtime package dependency: nativescript-optimized
         + adding aar plugin dependency: /Users/asrock/Documents/ns-layovers/node_modules/tns-core-modules-widgets/platforms/android/widgets-release.aar
Running full build
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForF0F1Debug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Unable to apply changes on device: emulator-5554. Error is: Command ./gradlew failed with exit code 1.
Executing after-watch hook from /Users/asrock/Documents/ns-layovers/hooks/after-watch/nativescript-dev-typescript.js
`

**Comment by manijak** [comment]
Hmmm strange. I just tested two of my apps plus the demo app with `3.3.1` without any issues. Could it be that your Android SDK is outdated or perhaps using a pre-release version?

**Comment by erjdriver** [comment]
It could be - but I was able to build another Android app.

But if you were able run it - then most probably on this end.

I'll close this for now.

**Comment by erjdriver** [comment]
Can you tell me what SDK - API you've got installed?

Also is Google Play Services required?

**Comment by manijak** [comment]
I've got 25,26,27, and no, play services are not required.

**Comment by manijak** [comment]
Plugin also tested od SDK 28 and TNS 4.x, working as usual.
