### ISSUE TITLE
Demo crashes on Android

### ISSUE THREAD

**Issue by terreb** [manijak/nativescript-carousel#6]
Somehow demo doesn't work on Android for me:( 

I'm trying to run the demo from the repo on Android emulator (Genymotion Samsung Galaxy S6 Android 5.1.0 API 22). It starts with no issues but when I click on any button it crashes showing the next:

An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onClick failed

[object Object]
File: "/data/data/org.carousel.demo/files/app/tns_modules/ui/builder/builder.js, line: 167, column: 20

StackTrace: 
	Frame: function:'', file:'/data/data/org.carousel.demo/files/app/tns_modules/ui/builder/builder.js', line: 167, column: 21
	Frame: function:'', file:'/data/data/org.carousel.demo/files/app/tns_modules/xml/xml.js', line: 148, column: 13
	Frame: function:'EasySAXParser.parse', file:'/data/data/org.carousel.demo/files/app/tns_modules/js-libs/easysax/easysax.js', line: 751, column: 23
	Frame: function:'XmlParser.parse', file:'/data/data/org.carousel.demo/files/app/tns_modules/xml/xml.js', line: 195, column: 22
	Frame: function:'XmlStringParser.parse', file:'/data/data/org.carousel.demo/files/app/tns_modules/ui/builder/builder.js', line: 173, column: 27
	Frame: function:'parseInternal', file:'/data/data/org.carousel.demo/files/app/tns_modules/ui/builder/builder.js', li...

My config:
    nativescript-cli: 2.4.0
    "tns-ios": "2.4.0"
    "tns-android":  "2.4.1"
    "nativescript-carousel": "file:.."
    "tns-core-modules": "^2.4.0"

Please let me know if you require any further info.

**Comment by manijak** [comment]
Can you confirm that this is still an issue. I just downloaded the master from here, added android as platform and it ran normally.

**Comment by terreb** [comment]
I removed the folder and git cloned again. It works now. I'm sorry for bothering you. It seems some local glitch. Sorry again, please close the issue.

**Comment by manijak** [comment]
Great, thanks for the confirmation.
