### ISSUE TITLE
no args.index when tap CarouselItem on Android

### ISSUE THREAD

**Issue by xingyuli** [manijak/nativescript-carousel#61]
tns version: 3.3.0
nativescript-carousel version: 3.1.1

xml:
```XML
<carousels:CarouselItem verticalAlignment="center" tap="onAdTap">
  <Image src="{{ image.url }}" stretch="aspectFill" />
</carousels:CarouselItem>
```

js:
```javascript
exports.onAdTap = function(args) {
    // outputs: tap ad at index undefined
    console.log('tap ad at index ' + args.index);
};
```

I debugged in VS Code, found no 'index' there.

**Comment by manijak** [comment]
Hi there, only `pageScrolling` and `pageChanged` have `args.index`. The `tap` event is the {N} native one, and it does not have `index` property. 

You could use the `selectedPage` property that returns the current page index, you just need an instance of the Carousel.

**Comment by xingyuli** [comment]
Thanks for pointing out the usage of `selectedPage` of the `Carousel` view. It works!

But for clarifying the tap behavior, I tested the two different approaches to respond the tap event both on Android(real device) and iOS(simulator):
- the 1st is the `pageTapped` on the `Carousel` tag (as it was shown in [demo3](https://github.com/manijak/nativescript-carousel/blob/master/demo/app/carousel3.xml)).
- and the 2nd is the `tap` event on the `CarouselItem` tag (as it was shown in the [plugins market](https://market.nativescript.org/plugins/nativescript-carousel)).

Here is event handler's code:
```javascript
exports.onTap = function(args) {
    console.log('tap at index ' + args.index);
    let selectedPage = page.getViewById('carousel').selectedPage;
    console.log('tap at selectedPage ' + selectedPage);
};
```

Testing result of `pageTapped` on `Carousel`:

| Value        | Android           | iOS  |
| ------------- |:-------------:| -----:|
| args.index      | _event not working_ | has correct value |
| carouselView.selectedPage      | _event not working_     |   has correct value |

Testing result of `tap` on `CarouselItem`:

| Value        | Android           | iOS  |
| ------------- |:-------------:| -----:|
| args.index      | _undefined_ | _undefined_ |
| carouselView.selectedPage      | has correct value      |   has correct value |

So I think you may pointing out the difference, or add doc for recommended approach for handling the tap event, on the plugin market (or npm package), as currently the doc and your demo3's xml and js is confusing this.

Your demo3 js' event handler use `index` property:
```js
exports.mySelectedEvent = function(args){
    var tappedViewText = "Tapped index: " + args.index;
    pageData.set("tappedViewText", tappedViewText);
}
```

**Comment by manijak** [comment]
You are right, this is something I added earlier, then removed. But only in the readme, forgot to update the demo. Thanks for letting me know.
