### ISSUE TITLE
Cannot run demo

### ISSUE THREAD

**Issue by pentool** [manijak/nativescript-carousel#63]
The demo project does not run.

1. I have downloaded the project zip file.
2. Unzip
3. Open the "demo" folder inside the project
4. npm install
5. tns run ios
6. I get the following output. Have to stop it with Ctrl+C

```
Project successfully created.
Preparing project...
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
...
```

TNS CLI: 3.4.1
iOS Simulator 9.3.1
Xcode 8.2.1
OS X 10.11.6

**Comment by pentool** [comment]
I'm curious why was this closed without any comment? The demo still doesn't run due to the above issue.

**Comment by manijak** [comment]
Just tested the demo, runs fine

**Comment by pentool** [comment]
Maybe it's the "...it works on my machine..." syndrome? :-)

I have described in my first post of how did I download and open the downloaded zip project file.

1. Open the unzipped 'nativescript-carousel-master' folder.
2. Drag the 'demo' folder onto VSCode to open it.
3. Open the console in VSCode (you will be automatically in your demo directory).
4. Use `npm install` to install the modules.
5. Expand the installed 'node_modules' folder in VSCode's file/directory browser.
6. Inside the 'node_modules' folder, expand the 'nativescript-carousel' folder. There will be another 'demo' folder inside it.
7. Expand that 'demo' folder. Inside it, there will be yet another 'node_modules' folder. And inside it, yet another 'nativescript-carousel' folder, and so on and so on...

And I think this is why I'm getting the error about 'Cycle link found' and the demo cannot compile.

**Comment by manijak** [comment]
Perhaps... anything is possible.  What version of node & npm are you using?

**Comment by pentool** [comment]
Node: 8.9.1
npm: 5.6.0

**Comment by manijak** [comment]
That could be the issue. As of npm 5.x it doesn't handle local dependencies very well. You can either move the plugin inside the demo folder and update the dependency or just update package.json to point to the deployed version.

- Nuke the node_modules, platform & hooks folders.
- Update the package.json in the demo-app: 
`"nativescript-carousel": "file:.."` 
to
`"nativescript-carousel": "3.1.1"`
- build & run

**Comment by pentool** [comment]
I did that. But it seems every time package.json pulls in the modules, the `nativescript-carousel` module keeps downloading the `demo > node_modules > nativescript-carousel > demo > node_modules > nativescript-carousel...>` etc and it keeps cycling.

**Comment by manijak** [comment]
If you install the plugin via npm it does not include any demo or node_modules folder. This is probably due to downloading the master repo and trying to run this directly from it.

Try this:
- Download the master repo & unpack
- Move the `demo` folder to another location on you disk
- Open the `demo` in VSCode and update package.json like mentioned above (3.1.1)
- Remove any `package-lock.json` if present.
- Build & run

**Comment by pentool** [comment]
That did the trick, thank you!
