### ISSUE TITLE
com.rd.PageIndicatorView is not a constructor, undefined

### ISSUE THREAD

**Issue by pradt** [manijak/nativescript-carousel#65]
Hi, 
I'm receiving a message "com.rd.PageIndicatorView is not a constructor, undefined" when I run my application.

My xml:
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd"  xmlns:ns="nativescript-carousel" navigatingTo="navigatingTo" class="page">
    <ns:Carousel height="250" >
        <ns:CarouselItem id="slide1"  verticalAlignment="center" backgroundColor="#b3cde0">
            <Label text="Slide 1" verticalAlignment="center" horizontalAlignment="center"/>
        </ns:CarouselItem>
        <ns:CarouselItem id="slide2" verticalAlignment="center" backgroundColor="#6497b1">
            <Label text="Slide 2" verticalAlignment="center" horizontalAlignment="center"/>
        </ns:CarouselItem>
        <ns:CarouselItem id="slide3" verticalAlignment="center" backgroundColor="#005b96">
            <Label text="Slide 3" verticalAlignment="center" horizontalAlignment="center"/>
        </ns:CarouselItem>
    </ns:Carousel>
</Page>
```

**Comment by locolauty97** [comment]
Same problem here, running tns 3.4.2 and tns-android 3.4.1

**Comment by geriskenderi** [comment]
Same problem over here as well.
The plugin runs fine on iOs but not on Android

**Comment by manijak** [comment]
I don't know what to tell you fellas... I ran the plugin just fine on the latest template.

Are you able to run the demo-app included in the plugin repo? From what I can tell based on the error you gave me, seems like the gradle didn't download the IndicatorView plugin. 

Check that you have the latest android sdk, or at least 26. Also try removing platform and nuking node_modules and hooks, then rebuild.

**Comment by locolauty97** [comment]
Hey @pradt I solved the problem by deleting the platforms and node_modules folders, and running `tns run android`.
Hope it helps

**Comment by geriskenderi** [comment]
Same for me, deleted the node_modules and platform folders and now it works.
Thank you everyone for your help 😄

**Comment by VladsGG** [comment]
i'm also experiencing this on 4.1.0, already deleted the node_modules and platforms
