### ISSUE TITLE
Plugin messing up with CSS

### ISSUE THREAD

**Issue by d3mac123** [manijak/nativescript-carousel#66]
After installing the plugin my app started to mess up with CSS positioning. Any idea why? 
Things like:
`mySpeedTag.style.marginTop = 10;`

are not working anymore.

Any plans to update the plugin to make it compatible with NS latest version (3.4.x)?

**Comment by manijak** [comment]
I am not sure what you mean by "messing up css". The plugin does not modify or affect the css engine at all. And the plugin works fully with TNS 4.x.
