### ISSUE TITLE
Does this plugin works with NS 4.1?

### ISSUE THREAD

**Issue by handoyo** [manijak/nativescript-carousel#69]
Hi, does this plugin works with NS 4.1? Thanks.

**Comment by manijak** [comment]
Is there some indication that it does not work on 4.1? Please provide more info if it does not work...

**Comment by manijak** [comment]
Just tested the demo app on 4.1.2 - everything working as it should. Closing.

**Comment by handoyo** [comment]
Hi, thanks for the info. Good to know that it works with 4.1.2.
