### ISSUE TITLE
Not working with navigatingTo on Android

### ISSUE THREAD

**Issue by terreb** [manijak/nativescript-carousel#7]
When adding bindingContext on page nativigatingTo event instead of loaded event no slides show up for me when I run the app on Android (Genymotion Samsung Galaxy S6 Android 5.1.0).

How to reproduce:

1. add navigatingTo="onNavigatingTo" to your page xml where you have carousel view

```xml
<Page xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:ns="nativescript-carousel" navigatingTo="onNavigatingTo">
  <!-- UI Decalration -->
  <ScrollView>
    <StackLayout>
      <Label text="test" backgroundColor="red" height="250"/>

      <GridLayout height="250">
        <ns:Carousel id="myCarousel" height="250" color="white" pageChanged="myChangeEvent" pageTapped="mySelectedEvent"
                     items="{{ myDataArray }}" indicatorColor="#fff" ios:autoPagingInterval="4" android:indicatorAnimation="fill">
          <ns:Carousel.itemTemplate>
            <ns:CarouselItem  verticalAlignment="center" backgroundColor="{{ color }}" height="250">
              <GridLayout rows="*" columns="*,*">
                <Label text="{{ title }}"  horizontalAlignment="center" verticalAlignment="center" col="0"/>
                <Image src="{{ image }}" height="100" col="1" />
              </GridLayout>
            </ns:CarouselItem>
          </ns:Carousel.itemTemplate>
        </ns:Carousel>
      </GridLayout>

      <Label text="test" backgroundColor="red" height="250"/>
    </StackLayout>
  </ScrollView>
</Page>
```

2. remove or comment out pageLoaded function in your code behind or loaded event in xml
3. add the next to the code behind

```javascript
var myDataArray = [
    {title:"Slide 1", color: "#b3cde0", image:"https://raw.githubusercontent.com/manijak/nativescript-photoviewer/master/demo/res/01.jpg"},
    {title:"Slide 2", color: "#6497b1", image:"https://raw.githubusercontent.com/manijak/nativescript-photoviewer/master/demo/res/02.jpg"},
    {title:"Slide 3", color: "#005b96", image:"https://raw.githubusercontent.com/manijak/nativescript-photoviewer/master/demo/res/03.jpg"},
    {title:"Slide 4", color: "#03396c", image:"https://raw.githubusercontent.com/manijak/nativescript-photoviewer/master/demo/res/04.jpg"}
];
pageData.set("myDataArray", myDataArray);
exports.onNavigatingTo = function(args) {
    var page = args.object;
    page.bindingContext = pageData;

    myCarousel = page.getViewById("myCarousel");
}
```

My config:
nativescript-cli 2.4.0
core-modules: 2.4.0
tns-android: 2.4.1
nativescript-carousel: 2.1.0

**Comment by manijak** [comment]
My I ask why you are trying to do all this in the `navigatingTo` event? A rule of thumb is not to do anything frame related in this event, since the UI isn't fully loaded yet. That is why the demo is using the `loaded` event. 

Read more here: http://fluentreports.com/blog/?p=191

**Comment by terreb** [comment]
Well, I thought I'm just binding a context to the view there, but not doing any direct UI mutations. I just follow what Telerik guys do in their demos, for example:
https://github.com/NativeScript/nativescript-marketplace-demo/blob/master/app/views/code-page.ts
They bind context on most of pages in navigatingTo event in that demo. Since navigatingTo fires earlier than loaded I thought the earlier I pass what I need is better:) Didn't know this is a bad practice, since it's working fine with all NS built-in components.

**Comment by manijak** [comment]
That is all nice and well, but you are not only binding the context, you are also fetching the Carousel view, which is probably not loaded yet.  
In the above example you have:
` myCarousel = page.getViewById("myCarousel");`

**Comment by terreb** [comment]
Ohh, this is one! It's not needed in loaded event indeed, but it's irrelevant for that use case anyway.

**Comment by manijak** [comment]
@terreb 
The reason for this is that when using the `onNavigatingTo` event, the UI modules have not been loaded yet. So the observable is updated but nothing is applied to the Carousel since the component is not there yet. 

Use the `loaded` event instead, that way you are sure that the UI modules are properly loaded. Otherwise you could wrap `pageData.set("myDataArray", myDataArray);` with a `setTimeout`.
