### ISSUE TITLE
Carousel is empty in nativescript-angular app

### ISSUE THREAD

**Issue by vahidvdn** [manijak/nativescript-carousel#77]
I'm working with a nativescript-angular app. I installed this plugin, and added code following the ng-demo to my existence project:

<GridLayout rows="40, auto, *, 50">
    <Label row="0" text="Text on the page in row 1 of grid" color="green" textWrap="true"></Label>

    <GridLayout row="2">
        <Carousel #carousel  ios:indicatorOffset="0,-10" ios:finite="true" ios:bounce="false" showIndicator="true" height="100%" indicatorAnimation="SWAP"
            indicatorColor="#66ccff" indicatorColorUnselected="#cceeff" height="250" width="80%">
            <CarouselItem backgroundColor="red" height="100%">
                <Label class="h2 text-center" color="white" textWrap="true" text="1"></Label>
            </CarouselItem>
            <CarouselItem backgroundColor="purple">
                <Label class="h2 text-center" color="white" textWrap="true" text="2"></Label>
            </CarouselItem>
        </Carousel>
    </GridLayout>

    <Label row="3" text="After 5 seconds the indicator animation will change to WORM on ANDROID" textWrap="true"></Label>
</GridLayout>

But I get the blank screen:

![photo_2018-08-03_14-06-35](https://user-images.githubusercontent.com/11078601/43636884-97d6b88e-9728-11e8-9e94-fe758aa087d3.jpg)

**Comment by corne-de-bruin** [comment]
Did you already registered the component in app.component.ts?

```
// Register Custom Elements for Angular
import { Carousel, CarouselItem } from 'nativescript-carousel';

registerElement('Carousel', () => Carousel);
registerElement('CarouselItem', () => CarouselItem);
```

**Comment by corne-de-bruin** [comment]
Hi @vahidvdn 

I've resolved that by changing my import as follow:
```
import * as elementRegistryModule from 'nativescript-angular/element-registry';
elementRegistryModule.registerElement('Carousel', () => require('nativescript-carousel').Carousel);
elementRegistryModule.registerElement('CarouselItem', () => require('nativescript-carousel').CarouselItem);
```

Looks like the typings aren't correct yet

**Comment by vahidvdn** [comment]
@corne-de-bruin Now there is no error, but still the same result.

**Comment by bradmartin** [comment]
Did you assign any position/size to the grid or carousel? This app uses the carousel plugin quite a bit and it renders https://github.com/PushTracker/EvalApp/blob/master/maxmobility/apps/eval-mobile/app/modules/training/training.component.html#L7 so maybe just some layout changes will solve @vahidvdn

**Comment by vahidvdn** [comment]
Hey @bradmartin 
Now it works fine in new project. I don't know what was the reason. Btw, thank you.
