### ISSUE TITLE
IndicatorOffset on Android used px instead of dp

### ISSUE THREAD

**Issue by bartsg** [manijak/nativescript-carousel#80]
On Android, the indicatorOffset is defined in pixels instead of density-independent pixels. I've tried to set it programatically on Android like this:

```javascript        
if (isAndroid) {
    // On Android, the indicator offset is defined in px instead of dp. Therefore, we have to convert it ourselves.
    const carousel = this.carouselRef.nativeElement as any;
    carousel.indicatorOffset = '0,-' + layout.toDevicePixels(60).toString();
}
```

```xml
<Carousel #carousel ios:indicatorOffset="0,-60">
</Carousel>
```

Using this fix, the indicator stays at the correct height on all platforms. I think that the desired behaviour should be that the input of the indicatorOffset attribute is defined in dp like it is on iOS.

**Comment by bartsg** [comment]
#81

**Comment by bartsg** [comment]
I've created a new PR from a different branch: #82

**Comment by manijak** [comment]
Thanks! Merged 👍
