### ISSUE TITLE
Implementation example using {N}+Vue?

### ISSUE THREAD

**Issue by Erwol** [manijak/nativescript-carousel#86]
Hello, I'd like to know if there's a guide bout how to use this plugin with Vue, instead of Angular or _vanila_ nativescript. Thanks! - Could add the #question label by myself.

**Comment by manijak** [comment]
Hi there. Just merged a PR to master that adds a demo for Vue, thanks to @suryaadtmaja 
Don't know if (or how) it works :)

**Comment by h-p-r** [comment]
check out  #94
