### ISSUE TITLE
Angular 2 & typescript - App Crashes when opened from the background

### ISSUE THREAD

**Issue by manishmlv50** [manijak/nativescript-carousel#9]
I am using nativescript with angular 2 and typescript. This works fine when the app is open. But it crashes when the app is in background and not killed and opened again. I have mentioned the log below. Please help. 

The following is the nativescript cli details:
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬──────────────────┐
│ Component        │ Current version │ Latest version │ Information      │
│ nativescript     │ 2.4.0           │ 2.4.2          │ Update available │
│ tns-core-modules │ 2.4.0           │ 2.4.3          │ Update available │
│ tns-android      │ 2.4.1           │ 2.4.1          │ Up to date       │
│ tns-ios          │ 2.4.0           │ 2.4.0          │ Up to date       │

I have registered the component in the app.module file as:

registerElement("CardView", () => require("nativescript-cardview").CardView);
registerElement("Carousel", () => require("nativescript-carousel").Carousel);
registerElement("CarouselItem", () => require("nativescript-carousel").CarouselItem);

Have used the following code in the my .html file:

        <Carousel height="250">
            <CarouselItem id="slide1" backgroundColor="#b3cde0" height="250">
            <Label text="Signup now and take advantege of this service!" verticalAlignment="center" horizontalAlignment="center"></Label>
            </CarouselItem>
            <CarouselItem id="slide2" verticalAlignment="center" backgroundColor="#6497b1" height="250">
            <Label text="Still in doubt? Come on!" verticalAlignment="center" horizontalAlignment="center"></Label>
            </CarouselItem>
            <CarouselItem id="slide3" verticalAlignment="center" backgroundColor="#005b96" height="250">
            <Label text="Signup now and I'll be your best friend!" verticalAlignment="center" horizontalAlignment="center"></Label>
            </CarouselItem>
        </Carousel>
    </StackLayout>

An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to resume activity {com.one.develop/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onStart failed

Error: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
    android.view.ViewGroup.addViewInner(ViewGroup.java:4310)
    android.view.ViewGroup.addView(ViewGroup.java:4146)
    android.view.ViewGroup.addView(ViewGroup.java:4087)
    android.view.ViewGroup.addView(ViewGroup.java:4060)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
    com.tns.Runtime.callJSMethod(Runtime.java:895)
    com.tns.Runtime.callJSMethod(Runtime.java:879)
    com.tns.Runtime.callJSMethod(Runtime.java:871)
    com.tns.NativeScriptActivity.onStart(android.app.Activity.java)
    android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
    android.app.Activity.performStart(Activity.java:6320)
    android.app.Activity.performRestart(Activity.java:6366)
    android.app.Activity.performResume(Activity.java:6371)
    android.app.ActivityThread.performResumeActivity(ActivityThread.java:3099)
    android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3141)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1395)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5441)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
File: "/data/data/com.one.develop/files/app/tns_modules/nativescript-carousel/index.js, line: 88, column: 36

StackTrace: 
	Frame: function:'Carousel.onLoaded', file:'/data/data/com.one.develop/files/app/tns_modules/nativescript-carousel/index.js', line: 88, column: 37
	Frame: function:'eachChild', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view-common.js', line: 748, column: 23
	Frame: function:'LayoutBase._eachChildView', file:'/data/data/com.one.develop/files/app/tns_modules/ui/layouts/layout-base-common.js', line: 144, column: 22
	Frame: function:'View._loadEachChildView', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view-common.js', line: 751, column: 18
	Frame: function:'View.onLoaded', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view-common.js', line: 741, column: 14
	Frame: function:'View.onLoaded', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view.js', line: 83, column: 35
	Frame: function:'eachChild', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view-common.js', line: 748, column: 23
	Frame: function:'LayoutBase._eachChildView', file:'/data/data/com.one.develop/files/app/tns_modules/ui/layouts/layout-base-common.js', line: 144, column: 22
	Frame: function:'View._loadEachChildView', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view-common.js', line: 751, column: 18
	Frame: function:'View.onLoaded', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view-common.js', line: 741, column: 14
	Frame: function:'View.onLoaded', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view.js', line: 83, column: 35
	Frame: function:'eachChild', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view-common.js', line: 748, column: 23
	Frame: function:'ContentView._eachChildView', file:'/data/data/com.one.develop/files/app/tns_modules/ui/content-view/content-view.js', line: 65, column: 13
	Frame: function:'Page._eachChildView', file:'/data/data/com.one.develop/files/app/tns_modules/ui/page/page-common.js', line: 285, column: 41
	Frame: function:'View._loadEachChildView', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view-common.js', line: 751, column: 18
	Frame: function:'View.onLoaded', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view-common.js', line: 741, column: 14
	Frame: function:'View.onLoaded', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view.js', line: 83, column: 35
	Frame: function:'Page.onLoaded', file:'/data/data/com.one.develop/files/app/tns_modules/ui/page/page-common.js', line: 53, column: 35
	Frame: function:'eachChild', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view-common.js', line: 748, column: 23
	Frame: function:'Frame._eachChildView', file:'/data/data/com.one.develop/files/app/tns_modules/ui/frame/frame-common.js', line: 335, column: 13
	Frame: function:'View._loadEachChildView', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view-common.js', line: 751, column: 18
	Frame: function:'View.onLoaded', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view-common.js', line: 741, column: 14
	Frame: function:'View.onLoaded', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view.js', line: 83, column: 35
	Frame: function:'ActivityCallbacksImplementation.onStart', file:'/data/data/com.one.develop/files/app/tns_modules/ui/frame/frame.js', line: 708, column: 22
	Frame: function:'NativeScriptActivity.onStart', file:'/data/data/com.one.develop/files/app/tns_modules/ui/frame/activity.js', line: 19, column: 25

	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3110)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3141)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1395)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5441)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
Caused by: com.tns.NativeScriptException: 
Calling js method onStart failed

Error: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
    android.view.ViewGroup.addViewInner(ViewGroup.java:4310)
    android.view.ViewGroup.addView(ViewGroup.java:4146)
    android.view.ViewGroup.addView(ViewGroup.java:4087)
    android.view.ViewGroup.addView(ViewGroup.java:4060)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
    com.tns.Runtime.callJSMethod(Runtime.java:895)
    com.tns.Runtime.callJSMethod(Runtime.java:879)
    com.tns.Runtime.callJSMethod(Runtime.java:871)
    com.tns.NativeScriptActivity.onStart(android.app.Activity.java)
    android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
    android.app.Activity.performStart(Activity.java:6320)
    android.app.Activity.performRestart(Activity.java:6366)
    android.app.Activity.performResume(Activity.java:6371)
    android.app.ActivityThread.performResumeActivity(ActivityThread.java:3099)
    android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3141)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1395)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5441)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
File: "/data/data/com.one.develop/files/app/tns_modules/nativescript-carousel/index.js, line: 88, column: 36

StackTrace: 
	Frame: function:'Carousel.onLoaded', file:'/data/data/com.one.develop/files/app/tns_modules/nativescript-carousel/index.js', line: 88, column: 37
	Frame: function:'eachChild', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view-common.js', line: 748, column: 23
	Frame: function:'LayoutBase._eachChildView', file:'/data/data/com.one.develop/files/app/tns_modules/ui/layouts/layout-base-common.js', line: 144, column: 22
	Frame: function:'View._loadEachChildView', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view-common.js', line: 751, column: 18
	Frame: function:'View.onLoaded', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view-common.js', line: 741, column: 14
	Frame: function:'View.onLoaded', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view.js', line: 83, column: 35
	Frame: function:'eachChild', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view-common.js', line: 748, column: 23
	Frame: function:'LayoutBase._eachChildView', file:'/data/data/com.one.develop/files/app/tns_modules/ui/layouts/layout-base-common.js', line: 144, column: 22
	Frame: function:'View._loadEachChildView', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view-common.js', line: 751, column: 18
	Frame: function:'View.onLoaded', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view-common.js', line: 741, column: 14
	Frame: function:'View.onLoaded', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view.js', line: 83, column: 35
	Frame: function:'eachChild', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view-common.js', line: 748, column: 23
	Frame: function:'ContentView._eachChildView', file:'/data/data/com.one.develop/files/app/tns_modules/ui/content-view/content-view.js', line: 65, column: 13
	Frame: function:'Page._eachChildView', file:'/data/data/com.one.develop/files/app/tns_modules/ui/page/page-common.js', line: 285, column: 41
	Frame: function:'View._loadEachChildView', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view-common.js', line: 751, column: 18
	Frame: function:'View.onLoaded', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view-common.js', line: 741, column: 14
	Frame: function:'View.onLoaded', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view.js', line: 83, column: 35
	Frame: function:'Page.onLoaded', file:'/data/data/com.one.develop/files/app/tns_modules/ui/page/page-common.js', line: 53, column: 35
	Frame: function:'eachChild', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view-common.js', line: 748, column: 23
	Frame: function:'Frame._eachChildView', file:'/data/data/com.one.develop/files/app/tns_modules/ui/frame/frame-common.js', line: 335, column: 13
	Frame: function:'View._loadEachChildView', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view-common.js', line: 751, column: 18
	Frame: function:'View.onLoaded', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view-common.js', line: 741, column: 14
	Frame: function:'View.onLoaded', file:'/data/data/com.one.develop/files/app/tns_modules/ui/core/view.js', line: 83, column: 35
	Frame: function:'ActivityCallbacksImplementation.onStart', file:'/data/data/com.one.develop/files/app/tns_modules/ui/frame/frame.js', line: 708, column: 22
	Frame: function:'NativeScriptActivity.onStart', file:'/data/data/com.one.develop/files/app/tns_modules/ui/frame/activity.js', line: 19, column: 25

	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
	at com.tns.Runtime.callJSMethod(Runtime.java:895)
	at com.tns.Runtime.callJSMethod(Runtime.java:879)
	at com.tns.Runtime.callJSMethod(Runtime.java:871)
	at com.tns.NativeScriptActivity.onStart(android.app.Activity.java)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
	at android.app.Activity.performStart(Activity.java:6320)
	at android.app.Activity.performRestart(Activity.java:6366)
	at android.app.Activity.performResume(Activity.java:6371)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3099)
	... 8 more
Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:4310)
	at android.view.ViewGroup.addView(ViewGroup.java:4146)
	at android.view.ViewGroup.addView(ViewGroup.java:4087)
	at android.view.ViewGroup.addView(ViewGroup.java:4060)
	... 20 more

**Comment by manijak** [comment]
So sorry about that, I haven't had time to publish a new version. Will do asap. 
Meanwhile a PR has been merged to master that will fix this issue. You can grab the latest from here and test if you want, or wait for release.

**Comment by manijak** [comment]
PR applied to latest release, 2.1.2.

**Comment by manishmlv50** [comment]
Hey @manijak Thank you. It worked (Y)

**Comment by manijak** [comment]
Great, thanks for letting me know. Closing.
