### ISSUE TITLE
pageTapped Event don't works on Android

### ISSUE THREAD

**Issue by oskarinn** [manijak/nativescript-carousel#96]
First, let me say thank you for this great plugin. Cheers!

I have a project where I am using this plugin with Nativescript 5.0.1 and Angular 7 and it works very well except the tap event on a page / slide, it does not work on Android, on iOS it works very well but on Android it does not do anything.

I appreciate any comments you can help me run the pageTapped event on android.

**Comment by oskarinn** [comment]
Thank you! Thats works for me!

Now, I am using the tap event to hide or show the indicator page (showIndicator property), in iOS it works very well but in Android it does not, this is my code. Any suggestions?

`onTapCarouselItem() {
        console.log("tap on item"); 
        const carousel = this.carouselRef.nativeElement as Carousel;
        carousel.showIndicator = !carousel.showIndicator;
    }`

**Comment by manijak** [comment]
Yeah it's not a bug, but just a missing feature in android. No easy way to hide the indicator, for now.
