### ISSUE TITLE
The reference path in index.d.ts is not correct

### ISSUE THREAD

**Issue by anmaitrannguyen** [manijak/nativescript-carousel#97]
NativeScript 5.0.2 version. npm 6.4.1 version, node 10.14.1 version.
nativescript-carousel 4.1.0.
For the index.d.ts file:
`/// <reference path="./node_modules/tns-platform-declarations/android.d.ts" />`
On window, when I try to build the app, it can not find the above file.
I have to go to the node_modules and change it to:
`/// <reference path="../tns-platform-declarations/android.d.ts" />`
To allow the app build success.

**Comment by akoua** [comment]
Please I'm the same error, can you help me. Thanks

**Comment by GeorgeRXia** [comment]
@anmaitrannguyen how were you able to fix this issue? What do you need to change in the node_modules?

**Comment by manijak** [comment]
Yeah the reference paths are only for when developing the plugin itself. they should have never been added to the index.d.ts file or included with the published package, will fix this. 

Also wise to make sure that your app and typescript don't analyse your `node_modules` folder. Set `"skipLibCheck": true` in your `tsconfig.json`
