### ISSUE TITLE
What is wrong here?

### ISSUE THREAD

**Issue by devWaleed** [manijak/nativescript-carousel#99]
<Page xmlns:ns="nativescript-carousel">
        <ns:Carousel height="100%" width="100%" pageChanged="myChangeEvent" pageTapped="mySelectedEvent"
                  indicatorColor="#fff000" finite="true" bounce="false" showIndicator="true"
                  verticalAlignment="top"  color="white">
            <ns:CarouselItem id="slide1" backgroundColor="#b3cde0" verticalAlignment="middle">
                <Label text="Slide 1" backgroundColor="#50000000" horizontalAlignment="center"/>
            </ns:CarouselItem>
            <ns:CarouselItem id="slide2" backgroundColor="#6497b1" verticalAlignment="middle">
                <Label text="Slide 2" backgroundColor="#50000000" horizontalAlignment="center"/>
            </ns:CarouselItem>
            <ns:CarouselItem id="slide3" backgroundColor="#005b96" verticalAlignment="middle">
                <Label text="Slide 3" backgroundColor="#50000000" horizontalAlignment="center"/>
            </ns:CarouselItem>
            <ns:CarouselItem id="slide4" backgroundColor="#03396c" verticalAlignment="middle">
                <Label text="Slide 4" backgroundColor="#50000000" horizontalAlignment="center"/>
            </ns:CarouselItem>
        </ns:Carousel>
    </Page>

Can someone explain me what is wrong here? I get error: No known component  for element ns:Carousel @manijak

**Comment by manijak** [comment]
Try and remove the platforms and then rebuild.

**Comment by manijak** [comment]
@devWaleed has the issue been resolved?

**Comment by devWaleed** [comment]
@manijak Sorry, I was in hurry so I moved to work with Cordova/Vue. Stopped working with NS.
